### ISSUE TITLE
 Exception: sh: cut: command not found

### ISSUE THREAD

**Issue by ankushgoel27** [mwrlabs/needle#1]
hi,

I am getting this error when i try to run any module. I believe the IOS doesn't have the 'cut' command installed.

**Comment by marco-lancini** [comment]
Hi, if you set the global variable `SETUP_DEVICE` to `True`, Needle will automatically install all the dependencies needed on the device:

```set SETUP_DEVICE True```

**Comment by ankushgoel27** [comment]
i did setup the setup_device True however no luck. I went to cydia and installed the required package from there. :)

**Comment by marco-lancini** [comment]
@ankushgoel27 what package did you have to install?
