### ISSUE TITLE
Errors parsing a plist file which itself contains a nested binary plist file

### ISSUE THREAD

**Issue by tghosth** [mwrlabs/needle#102]
Hi, @marco-lancini. I have a plist file which appears to contain another binary format plist file nested within it.

bplist appears to convert the file to a dict object with the nested file staying in an encoded binary format, This is then causing errors when the file is serialized to JSON because it cannot convert the encoded binary to an appropriate format.

Have you seen anything like this?

My suggested solution would be to try and do the plist parsing recursively, searching for the "bplist0" keyword at the start of a plist value . Does this sound sensible? If so, I will try and have a go.

**Comment by marco-lancini** [comment]
Hi @tghosth, yes please!
Give it a go! :)

**Comment by tghosth** [comment]
Opened PR #105
