### ISSUE TITLE
root permission denied : for module binary/install

### ISSUE THREAD

**Issue by pragyan1994** [mwrlabs/needle#106]
## Issue
Even after putting the ipa in the folder specified i.e /var/root/needle/app.ipa, the application is not able to install the ipa.

### Expected behaviour
Automatically upload and install an IPA on the device

### Actual behaviour
Gives an error saying : root permission denied

### Steps to reproduce
1. show modules
2.use  binary/install
3.set path for IPA
4.run

### needle error logs
needle] > use binary/install
[needle][install] > /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa 
[*] Executing Local Command: /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa
[D] [LOCAL CMD] Local Command: /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa
/bin/sh: /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa: Permission denied

#### Workstation Operating System
OSX 10.10.5

#### Python Version
2.7.10

#### Device iOS Version
8.1.2

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files to this thread and we can assist further.

**Comment by pragyan1994** [comment]
needle] > use binary/install
[needle][install] > /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa 
[*] Executing Local Command: /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa
[D] [LOCAL CMD] Local Command: /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa
/bin/sh: /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa: Permission denied

**Comment by marco-lancini** [comment]
Hi @pragyan1994, I suggest you to read the project wiki (https://github.com/mwrlabs/needle/wiki) to learn how to use needle :)

In your example, I think you would like to do:

```
[needle][install] > set IPA /Users/akanksha.bana/Desktop/ipa/YOVOPLE.ipa
[needle][install] > run
```

**Comment by pragyan1994** [comment]
IPA is set
it asks me to put the ipa inside var/needle/ to which i dont have a permission

**Comment by marco-lancini** [comment]
Can you please post the full error log? I don't see such error from the log you posted above

**Comment by pragyan1994** [comment]
Installing binary...
[D] [REMOTE CMD] Remote Interactive TTY Command: ipainstaller /var/root/needle/app.ipa
Warning: Permanently added '[localhost]:2229' (RSA) to the list of known hosts.
File not found at path: /var/root/needle/app.ipa.
Please specify any IPA file(s) to install.
Connection to localhost closed.
[needle][install] > 



if i directly try to install from any random space of my system, desktop or so.
It is expecting the ipa to be inside  /var/root/needle/app.ipa, inferred from "File not found at path: /var/root/needle/app.ipa."

**Comment by marco-lancini** [comment]
You don't need to manually put the IPA anywhere on device, after you `set IPA path/on/your/local/workstation`,   needle will automatically push the IPA on device and install it

**Comment by pragyan1994** [comment]
Then this is the error i am getting anyway 


Options:
  Name  Current Value                                                      Required  Description
  ----  -------------                                                      --------  -----------
  IPA   /Users/pragyan.a.paramita/Desktop/DamnVulnerableiOSApp\ \(1\).ipa  yes       Full path of the IPA to install

[needle][install] > run
[*] Checking connection with device...
[+] Already connected to: localhost
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[V] Uploading binary: /Users/pragyan.a.paramita/Desktop/DamnVulnerableiOSApp\ \(1\).ipa
[D] Uploading: "'/Users/pragyan.a.paramita/Desktop/DamnVulnerableiOSApp\ \(1\).ipa'" -> "/var/root/needle/app.ipa"
[D] [LOCAL CMD] Local Command: sshpass -p "alpine321" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2229 -r "'/Users/pragyan.a.paramita/Desktop/DamnVulnerableiOSApp\ \(1\).ipa'" root@localhost:"/var/root/needle/app.ipa"
[V] Installing binary...
[D] [REMOTE CMD] Remote Interactive TTY Command: ipainstaller /var/root/needle/app.ipa
Warning: Permanently added '[localhost]:2229' (RSA) to the list of known hosts.
File not found at path: /var/root/needle/app.ipa.
Please specify any IPA file(s) to install.
Connection to localhost closed.
[needle][install] >

**Comment by marco-lancini** [comment]
ok, this makes sense. Can you please try to rename the IPA so to remove the `(1)` bit?

**Comment by kryptoknight13** [comment]
yes, it works after renaming the ipa (removing spaces/special characters).
thanks!

on different note: i would like to suggest one enhancement, where either you can implement a script for removing the unwanted spaces/special characters in ipa name OR throw an error to user notifying for renaming the application name.
let me know if i need to raise separate enhancement request? 

thanks in advance.

**Comment by pragyan1994** [comment]
[?] Trying to continue anyway...
[V] Uploading binary: /Users/pragyan.a.paramita/Desktop/DVIA.ipa
[V] Installing binary...
Warning: Permanently added '[localhost]:2226' (RSA) to the list of known hosts.
File not found at path: /var/root/needle/app.ipa.
Please specify any IPA file(s) to install.
Connection to localhost closed.
[needle][install] > 


i am getting this error still .

**Comment by pragyan1994** [comment]
[?] Trying to continue anyway...
[V] Uploading binary: /Users/pragyan.a.paramita/Desktop/DVIA.ipa
[V] Installing binary...
Warning: Permanently added '[localhost]:2226' (RSA) to the list of known hosts.
File not found at path: /var/root/needle/app.ipa.
Please specify any IPA file(s) to install.
Connection to localhost closed.
[needle][install] > 



i have updated needle as well, but then i am still getting this error.

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files to this thread and we can assist further.

**Comment by pragyan1994** [comment]
[needle] > use  binary/install
[needle][install] > show info

      Name: Install IPA
      Path: modules/binary/install.py
    Author: @LanciniMarco (@MWRLabs)

Description:
  Automatically upload and install an IPA on the device

Options:
  Name  Current Value  Required  Description
  ----  -------------  --------  -----------
  IPA                  yes       Full path of the IPA to install

op/DVIA.ipa tall] > set IPA /Users/pragyan.a.paramita/Deskt 
IPA => /Users/pragyan.a.paramita/Desktop/DVIA.ipa
[needle][install] > show options

  Name  Current Value                               Required  Description
  ----  -------------                               --------  -----------
  IPA   /Users/pragyan.a.paramita/Desktop/DVIA.ipa  yes       Full path of the IPA to install

[needle][install] > run
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up USB port forwarding on port 2226
[V] Setting up SSH connection...
[+] Connected to: localhost
[V] Creating temp folder: /var/root/needle/
[*] Configuring device...
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://pepper.net ./ Release: The following signatures were invalid: NODATA 1 NODATA 2
W: Failed to fetch http://pepper.net/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://pepper.net ./ Release: The following signatures were invalid: NODATA 1 NODATA 2
W: Failed to fetch http://pepper.net/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...
[V] Uploading binary: /Users/pragyan.a.paramita/Desktop/DVIA.ipa
[V] Installing binary...
Warning: Permanently added '[localhost]:2226' (RSA) to the list of known hosts.
File not found at path: /var/root/needle/app.ipa.
Please specify any IPA file(s) to install.
Connection to localhost closed.
[needle][install] >

**Comment by marco-lancini** [comment]
Please ensure both VERBOSE and DEBUG mode are enabled

**Comment by pragyan1994** [comment]
Yes all of them are enabled

**Comment by marco-lancini** [comment]
Hi @kryptoknight13, yes please, open a different request regarding https://github.com/mwrlabs/needle/issues/106#issuecomment-270367760

**Comment by marco-lancini** [comment]
Hi @pragyan1994, no, even in your last dump I can't see any DEBUG output. Could you please enable it and re-post the full log please?

**Comment by pragyan1994** [comment]
[needle] > show options

  Name          Current Value  Required  Description
  ------------  -------------  --------  -----------
  APP                          no        Bundle ID of the target application (e.g., com.example.app). Leave empty to launch wizard
  DEBUG         False          yes       Enable debugging output
  IP            127.0.0.1      yes       IP address of the testing device (set to localhost to use USB)
  PASSWORD      alpine         yes       SSH Password of the testing device
  PORT          2222           yes       Port of the SSH agent on the testing device (needs to be != 22 to use USB)
  PROXY                        no        Proxy server (address:port)
  SETUP_DEVICE  True           yes       Set to true to enable auto-configuration of the device (installation of all the tools needed)
  USERNAME      root           yes       SSH Username of the testing device
  VERBOSE       True           yes       Enable verbose output

[needle] > set DEBUG True
DEBUG => True
[needle] > set IP localhost
IP => localhost
[needle] > set PASSWORD alpine321
PASSWORD => alpine321
[needle] > set PORT 2227
PORT => 2227






The result log

[needle] > use binary/install
[needle][install] > show info

      Name: Install IPA
      Path: modules/binary/install.py
    Author: @LanciniMarco (@MWRLabs)

Description:
  Automatically upload and install an IPA on the device

Options:
  Name  Current Value  Required  Description
  ----  -------------  --------  -----------
  IPA                  yes       Full path of the IPA to install

op/DVIA.ipa tall] > set IPA /Users/pragyan.a.paramita/Deskt 
IPA => /Users/pragyan.a.paramita/Desktop/DVIA.ipa
[needle][install] > show info

      Name: Install IPA
      Path: modules/binary/install.py
    Author: @LanciniMarco (@MWRLabs)

Description:
  Automatically upload and install an IPA on the device

Options:
  Name  Current Value                               Required  Description
  ----  -------------                               --------  -----------
  IPA   /Users/pragyan.a.paramita/Desktop/DVIA.ipa  yes       Full path of the IPA to install

[needle][install] > run
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up USB port forwarding on port 2227
[D] [LOCAL CMD] Local Subprocess Command: /Users/pragyan.a.paramita/needle/needle/libs/usbmuxd/tcprelay.py -t 22:2227
[V] Setting up SSH connection...
[+] Connected to: localhost
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[*] Configuring device...
[D] [REMOTE CMD] Remote Command: which apt-get
[D] [REMOTE CMD] Remote Command: which dpkg
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://pepper.net ./ Release: The following signatures were invalid: NODATA 1 NODATA 2
W: Failed to fetch http://pepper.net/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...
[D] [INSTALL] Installing COREUTILS via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes coreutils
[D] [INSTALL] Installing COREUTILS via apt-get.
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes coreutils-bin
[D] [REMOTE CMD] Remote Command: dpkg --get-selections | grep -v "deinstall" | cut -f1
[D] [REMOTE CMD] Remote Command: apt-get update
[?] Error occurred during apt-get update: bzip2: (stdin) is not a bzip2 file.
W: GPG error: http://repo.nesolabs.de ./ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F5266226F1ADFFA2
W: GPG error: http://pepper.net ./ Release: The following signatures were invalid: NODATA 1 NODATA 2
W: Failed to fetch http://pepper.net/./Packages.bz2  Sub-process /bin/bzip2 returned an error code (2)

E: Some index files failed to download, they have been ignored, or old ones used instead.
[?] Trying to continue anyway...
[D] [REMOTE CMD] Remote Command: cat /etc/apt/sources.list.d/cydia.list
[D] [REMOTE CMD] Remote Command: which FileDP
[D] [INSTALL] Tool already available: FILEDP
[D] Installation method not provided for UIOPEN. Skipping
[D] [INSTALL] Already installed: COREUTILS.
[D] [INSTALL] Already installed: COREUTILS.
[D] Installation method not provided for APT-GET. Skipping
[D] [INSTALL] Already installed: FRIDA.
[D] [INSTALL] Already installed: OPEN.
[D] Installation method not provided for FIND. Skipping
[D] Installation method not provided for OTOOL. Skipping
[D] Installation method not provided for UNZIP. Skipping
[D] [REMOTE CMD] Remote Command: which fsmon
[D] [INSTALL] Tool already available: FSMON
[D] [INSTALL] Already installed: DARWINTOOLS.
[D] [INSTALL] Already installed: CYCRIPT.
[D] [INSTALL] Already installed: BIGBOSS.
[D] [INSTALL] Already installed: SOCAT.
[D] Installation method not provided for LIPO. Skipping
[D] [INSTALL] Already installed: PLUTIL.
[D] Installation method not provided for WHICH. Skipping
[D] [INSTALL] Already installed: KEYCHAINDUMPER.
[D] [REMOTE CMD] Remote Command: which pbwatcher
[D] [INSTALL] Tool already available: PBWATCHER
[D] Installation method not provided for STRINGS. Skipping
[D] Installation method not provided for DPKG. Skipping
[D] [INSTALL] Already installed: IPAINSTALLER.
[D] [INSTALL] Already installed: CLASS-DUMP.
[D] [INSTALL] Already installed: CLASS-DUMP.
[D] [INSTALL] Already installed: CLASS-DUMP.
[D] [INSTALL] Already installed: GDB.
[D] [INSTALL] Already installed: CLUTCH.
[D] [INSTALL] Already installed: LDID.
[V] Uploading binary: /Users/pragyan.a.paramita/Desktop/DVIA.ipa
[D] Uploading: "/Users/pragyan.a.paramita/Desktop/DVIA.ipa" -> "/var/root/needle/app.ipa"
[D] [LOCAL CMD] Local Command: sshpass -p "alpine321" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2227 -r "/Users/pragyan.a.paramita/Desktop/DVIA.ipa" root@localhost:"/var/root/needle/app.ipa"
[V] Installing binary...
[D] [REMOTE CMD] Remote Interactive TTY Command: ipainstaller /var/root/needle/app.ipa
Warning: Permanently added '[localhost]:2227' (RSA) to the list of known hosts.
File not found at path: /var/root/needle/app.ipa.
Please specify any IPA file(s) to install.
Connection to localhost closed.
[needle][install] >

**Comment by marco-lancini** [comment]
If you open a terminal on your workstation (without using needle), and type this command:

`sshpass -p "alpine321" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2227 -r "/Users/pragyan.a.paramita/Desktop/DVIA.ipa" root@localhost:"/var/root/needle/app.ipa"`

Can you then find a file named `app.ipa` on your device in the `/var/root/needle/` folder?

**Comment by pragyan1994** [comment]
AMAC02KN29EFFT1:~ pragyan.a.paramita$ sshpass -p "alpine321" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 2227 -r "/Users/pragyan.a.paramita/Desktop/DVIA.ipa" root@localhost:"/var/root/needle/app.ipa"
Warning: Permanently added '[localhost]:2227' (RSA) to the list of known hosts.


I dont see any app.ipa in the device.

**Comment by marco-lancini** [comment]
Ok, so this confirms the issue is not within needle, but it seems you can't get a connection to the device at all

**Comment by pragyan1994** [comment]
this is more of an issue with my root permissions on the machine i guess. 
And i did have a connection with the device, with USB mux .

**Comment by marco-lancini** [comment]
ok, as you said this seems to be related with problems accessing your jailbroken device and is not related to needle
