### ISSUE TITLE
Installation of wrong frida package on 32 bit devices

### ISSUE THREAD

**Issue by smhome** [mwrlabs/needle#111]
## Issue
Wrong frida package on 32 bit devices gets installed.

### Expected behaviour
The installation of FRIDA should be dependent on the CPU architecture of the iOS device (i.e. 32 or 64 bit). In case of a 64 bit device the package "re.frida.server" should be installed whereas package "re.frida.server32" should be applied for 32 bit devices.  Both are available from repo "https://build.frida.re/".

### Actual behaviour
Having a 32 bit device, the wrong frida package gets installed when the global option SETUP_DEVICE is enabled.

### Steps to reproduce (32 bit devices only)
1. Enable auto-config of the device using "set SETUP_DEVICE True"
2. Run any module to start the auto-configuration of the device
3. frida (for 64 bit devices) gets installed

### Current workaround
Install "Frida for 32-bit devices" from Cydia and make sure auto-config is disabled (set global option SETUP_DEVICE to False) before running any (frida) module.

### needle error logs
```
[needle][script_enum-classes] > run
[*] Checking connection with device...
[+] Already connected to: <ip-address>
[V] Creating temp folder: /var/root/needle/
[+] Target app: <target-app-identifier>
[*] Local port forwarding to enable communications with the Frida server already setup
[*] Launching the app...
[V] Retrieving the PID...
[V] PID found: <pid>
[*] Attaching to process: <pid>
2017-01-17 15:31:13,670| ERROR   | Secsh channel 1 open FAILED: Connection refused: Connect failed
2017-01-17 15:31:13,675| ERROR   | Could not establish connection from ('127.0.0.1', 27042) to remote side of the tunnel
[!] ServerNotRunningError: unable to connect to remote frida-server: Unexpected lack of content trying to read a line.
```

#### Device iOS Version
iPhone 4S running jailbreaked iOS 9.0.2

**Comment by marco-lancini** [comment]
Hi @smhome, thanks for the suggestion. We will surely going to add a fix for this

**Comment by marco-lancini** [comment]
Hi @smhome, sorry for the delay. This has now been fixed with the new  `device/dependency_installer` module, which offers more granular support towards installation of dependencies
