### ISSUE TITLE
dyld: Symbol not found: _map_fd 

### ISSUE THREAD

**Issue by sowdust** [mwrlabs/needle#116]
## Issue
When trying to run a module on any application , i get an exception that keeps me from executing it.
It happens when needle tries to retrieve an app's metadata.
The exception error is: 
```
dyld: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: /usr/lib/libSystem.B.dylib
```

It happens just after the line 
`[REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/APPID-479D-443F-BC83-7CA2DA42C1F6/APPName.app/APPName`

Full stack trace is: 
```
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/needle/needle/core/framework/module.py", line 112, in do_run
    pre = self.module_pre()
  File "/opt/needle/needle/core/framework/module.py", line 144, in module_pre
    if self.app_check() is None: return None
  File "/opt/needle/needle/core/framework/framework.py", line 692, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/opt/needle/needle/core/device/app.py", line 20, in get_metadata
    return self._retrieve_metadata()
  File "/opt/needle/needle/core/device/app.py", line 65, in _retrieve_metadata
    architectures = self._detect_architectures(binary_path)
  File "/opt/needle/needle/core/device/app.py", line 96, in _detect_architectures
    out = self._device.remote_op.command_blocking(cmd, internal=True)
  File "/opt/needle/needle/core/device/remote_operations.py", line 93, in command_blocking
    out, err = self._device._exec_command_ssh(cmd, internal)
  File "/opt/needle/needle/core/device/device.py", line 123, in _exec_command_ssh
    raise Exception(err_str)
Exception: dyld: lazy symbol binding failed: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _map_fd
  Referenced from: /usr/bin/lipo
  Expected in: /usr/lib/libSystem.B.dylib


------------------------------------------------------------
[!]   Expected in: /usr/lib/libSystem.B.dylib.
```

It happens using the last version of needle just cloned from the repo and installed on kali following the installation guide.
The device is an iPhone 5 with iOS 8.2 (12D508).
Apt-get is installed as well as Darwin CC.

I noticed this problem is a duplicate of https://github.com/mwrlabs/needle/issues/11 but the author closed the issue without any further explanation.

**Comment by marco-lancini** [comment]
Hi,
have you tried to run lipo manually?

```lipo -info /private/var/mobile/Containers/Bundle/Application/APPID-479D-443F-BC83-7CA2DA42C1F6/APPName.app/APPName```

Is it failing?

**Comment by sowdust** [comment]
Yes it is. Seems like lipo is missing

**Comment by marco-lancini** [comment]
have you run needle with `SETUP_DEVICE` set to `True`?

**Comment by sowdust** [comment]
I had but it failed. After successfully running setup device the error disappears and modules work correctly. Thanks for the help, hopefully this will serve for future references. Ciao
