### ISSUE TITLE
setup - clutch2 installation error

### ISSUE THREAD

**Issue by ejohn20** [mwrlabs/needle#117]
## Issue
When setting up the device (set SETUP_DEVICE True), the auto install of cluth2 fails. It appears that this package is no longer found in the repository. Details below...

### Actual behaviour
[V] [INSTALL] Installing CLUTCH via apt-get.
[D] Adding repo to cydia.list: http://cydia.iphonecake.com/
[D] [REMOTE CMD] Remote Command: echo "deb http://cydia.iphonecake.com/ ./" >> /etc/apt/sources.list.d/cydia.list
[D] [REMOTE CMD] Remote Command: apt-get update
[D] [REMOTE CMD] Remote Command: apt-get install -y --force-yes com.iphonecake.clutch2
[?] Error occurred during installation of tools: E: Couldn't find package com.iphonecake.clutch2
[?] Trying to continue anyway...

### Steps to reproduce
1.Run the list_apps module on a new device and watch the output

### Proposed fix
I ran the following commands through the shell to install clutch2. Maybe it's worth updating the script to do this instead?

curl -ksL "http://cydia.iphonecake.com/Clutch2.0.4.deb" -o /var/root/kill.deb
dpkg -i /var/root/kill.deb && rm -f /var/root/kill.deb
killall -HUP SpringBoard

#### Workstation Operating System
Mac OS 10.11.6

#### Python Version
2.7.12
#### Python Packages (`pip freeze`)
astroid==1.4.9
awscli==1.11.30
backports.functools-lru-cache==1.3
boto3==1.4.2
botocore==1.4.87
c7n==0.8.21.2
cffi==1.8.3
colorama==0.3.7
configparser==3.5.0
cryptography==1.5.2
docutils==0.13.1
enum34==1.1.6
frida==8.1.1
functools32==3.2.3.post2
futures==3.0.5
idna==2.1
ipaddress==1.0.17
isort==4.2.5
jmespath==0.9.0
jsonschema==2.5.1
lazy-object-proxy==1.2.2
mccabe==0.5.3
paramiko==2.0.2
prompt-toolkit==1.0.8
pyasn1==0.1.9
pycparser==2.14
Pygments==2.1.3
pylint==1.6.4
python-dateutil==2.6.0
PyYAML==3.11
readline==6.2.4.1
rsa==3.4.2
s3transfer==0.1.10
six==1.10.0
skew==0.16.1
sshtunnel==0.1.1
wcwidth==0.1.7
wrapt==1.10.8

#### Device iOS Version
Jailbroken 10.1 device *

* I realized that 10.1 is not supported yet, I'll be adding details to the open 10.1 ticket if I can find the missing file.

**Comment by marco-lancini** [comment]
Hi, this has temporarily been fixed in `develop` using the suggested solution.
Long term Clutch will be replaced by the agent
