### ISSUE TITLE
AppSync install

### ISSUE THREAD

**Issue by tghosth** [mwrlabs/needle#119]
ipainstaller seems to rely on AppSync Unified being installed but needle does not seem to install this as part of setup. Should it do so? See, [here](http://www.ios9cydia.com/appsync.html).

Note that installing AppSync on iOS 10 apparently makes the device boot loop....!

**Comment by marco-lancini** [comment]
Hi @tghosth, I'll avoid this since AppSync is not stable on iOS 10.
Plus, with the release of the agent we might be able to replace ipainstaller completely
