### ISSUE TITLE
keychain_dump_frida user presence not working as intented

### ISSUE THREAD

**Issue by bernard-wagner** [mwrlabs/needle#121]
### Expected behaviour
Dump user presence values such as kSecTouchIDAny or kSecAccessControlTouchIDCurrentSet
### Actual behaviour
Attempts to read musr property which does not always work and does not parse the actual ACL
https://github.com/mwrlabs/needle/blob/develop/needle/modules/storage/data/keychain_dump_frida.py#L63

### Steps to reproduce
1. Run against application with keychains items that have User Presence set
2. Observe crash or UserPresence set to No 

## Fix 

Working on it, just need to tidy up output.

**Comment by marco-lancini** [comment]
Hi @bernard-wagner, any update on this? I'm about to release Needle v1.0 in a few days, and I'd like to include this fix! :)
