### ISSUE TITLE
Frida Attach or Spawn

### ISSUE THREAD

**Issue by HenryHoggard** [mwrlabs/needle#130]
It would be useful to have the option in Frida modules to either *attach to* or *spawn* a process. Currently it only gives an option to spawn the process, consequently restarting the application whenever a Frida script is run.

**Spawn**
```
[needle] use hooking/frida/script_frida-whatever
[needle] set mode spawn
[needle] run
```
**Attach**
```
[needle] use hooking/frida/script_frida-whatever
[needle] set mode attach
[needle] run
```

**Comment by marco-lancini** [comment]
Hi @HenryHoggard this has now been implemented in `develop`
