### ISSUE TITLE
constants.py: Clutch2 no longer hosted on http://cydia.iphonecake.com/

### ISSUE THREAD

**Issue by n0ttab0t** [mwrlabs/needle#144]
## Issue
Repo http://cydia.iphonecake.com/ now uses Rasticrac and has pulled Clutch2 from their repository. Thus, SETUP_DEVICE fails to install Clutch2.

## Solution
Change search path and package name in constants.py to a repo of your choosing.

**Comment by marco-lancini** [comment]
Duplicate of #117
