### ISSUE TITLE
Needle Agent Usecases

### ISSUE THREAD

**Issue by kryptoknight13** [mwrlabs/needle#146]
### Issue
Can you please list the use-cases of Needle Agent? How and what are the difference between previous version of needle and latest version of needle in accordance with needle agent?

**Comment by marco-lancini** [comment]
Hi, an overview was presented in the release blog post: http://mobiletools.mwrinfosecurity.com/Needle-1-0-0/

> The agent will allow needle to provide transparent support for iOS 10 (and future versions), and, over time, it will allow us to replace all dependencies required now (such as class-dump and keychain_dumper).

**Comment by marco-lancini** [comment]
Does this answer your question?

**Comment by kryptoknight13** [comment]
yes @marco-lancini! I was away from machine so couldn't reply. Thanks!
