### ISSUE TITLE
Readline issue (Solution attached)

### ISSUE THREAD

**Issue by javixeneize** [mwrlabs/needle#147]
Hi

Happy to see a new version of Needle. I just realised i am still using 0.0.3!

I had some problems with readline library in OSx:

ImportError: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so, 2): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib

If anybody is experiencing this issue, you just need to link the right file

ln -s /usr/local/opt/readline/lib/libreadline.7.0.dylib /usr/local/opt/readline/lib/libreadline.6.dylib

Thanks for keep improving needle. I will spend some time later on it :)

**Comment by marco-lancini** [comment]
Hi @javixeneize, thank you for taking the time to report it, as it may be helpful to other users.
I'm going to close this for now, since it is not related to needle itself.
