### ISSUE TITLE
Error While Pulling IPA

### ISSUE THREAD

**Issue by c0d3xpl0it** [mwrlabs/needle#150]
We encountered below error while pulling IPA from device over USB.

Options:
  Name         Current Value                 Required  Description
  -----------  -------------                 --------  -----------
  DECRYPT      True                          no        Set to True to decrypt the IPA before pulling
  OUTPUT       /root/.needle/output/app.ipa  yes       Full path of the output file
  PULL_BINARY  False                         no        Set to True to pull the application binary as well separately

[needle][pull_ipa] > run
[*] Checking connection with device...
[+] Already connected to: 127.0.0.1
[+] Target app: com.chnologies.ani
[*] Decrypting the binary...
[?] The app might be already decrypted. Trying to retrieve the IPA...
[!] KeyError: 'IPAINSTALLER'.
[needle][pull_ipa] >

**Comment by marco-lancini** [comment]
Hi @c0d3xpl0it, you'll have to install some dependencies before using needle.

See https://github.com/mwrlabs/needle/issues/1 and the [user guide](https://github.com/mwrlabs/needle/wiki/Quick-Start-Guide) before trying to use needle

**Comment by SubzeroiOS** [comment]
@c0d3xpl0it How did you resolve the issue (_[!] KeyError: 'IPAINSTALLER'._)?  I am also facing the same issue. I updated the dependencies by setting '''set SETUP_DEVICE True''' but still get the error while running _binary/reversing/strings_

**Comment by c0d3xpl0it** [comment]
I didnt get the solution for this issue.

**Comment by SubzeroiOS** [comment]
@c0d3xpl0it In case you are still interested, I could circumvent the issue by installing the v1.1.0 of needle (https://github.com/mwrlabs/needle/releases/tag/v1.1.0) and running Dependency Installer	(device/dependency_installer).

**Comment by c0d3xpl0it** [comment]
Aaah, thanks. I was running v1.0.2. Didnt notice the new release. Just FYI 1.2.0 is out.

**Comment by c0d3xpl0it** [comment]
@marco-lancini The new needle version **set SETUP_DEVICE True** is removed ?

**Comment by marco-lancini** [comment]
Exactly, it has been replaced by `device/dependency_installer`: https://github.com/mwrlabs/needle/wiki/Quick-Start-Guide
