### ISSUE TITLE
Show device IP in NeedleAgent 

### ISSUE THREAD

**Issue by tghosth** [mwrlabs/needle#165]
## Issue
Would be great if NeedleAgent could show the device's IP to save having to go find it :)

### Expected behaviour
NeedleAgent main screen should show device IP

### Actual behaviour
It does not

### Steps to reproduce
1. Open NeedleAgent

#### Device iOS Version
9.2.1

**Comment by marco-lancini** [comment]
Hi @tghosth, welcome back! :)
Good idea, I've just implemented it and pushed it into the `develop` branch of needle-agent

**Comment by tghosth** [comment]
Cheers @marco-lancini, is there a compiled version of the development branch?

**Comment by marco-lancini** [comment]
Not for the development branch
