### ISSUE TITLE
not able to run needle modules and get output on iPad iOS 9.3.1

### ISSUE THREAD

**Issue by null0x4d5a** [mwrlabs/needle#171]
## Issue
Not able to run modules using needle on iOS 9.3.1 

### Expected behaviour
As per basic usage of modules, it should run and fetch some output to console 

### Actual behaviour
not able to run needle modules and get output on iPad iOS 9.3.1. I have set up needle on kali by pulling latest from github and also installed agent 1.0.3 on my JB device ipad2 ios 9.3.1 but not able to use modules. When I hit run for any module it;s getting stuck and nothing is happening at all. I'll have to manually stop using Ctr+c 

### Steps to reproduce
1.
2.
3.

### needle error logs
Ensure verbose and debug mode are enabled:
![ios needle](https://cloud.githubusercontent.com/assets/14013208/26345499/b7c48bbe-3fc0-11e7-96ae-24503eed35c2.png)

```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

#### Needle Version

- Framework (on your machine): from https://github.com/mwrlabs/needle - 1.2.0
- Agent (on your device): agent 1.0.3

#### Workstation Operating System
Kali Linux 

#### Python Version
2.7
#### Python Packages (`pip freeze`)
adns-python==1.2.1
AdvancedHTTPServer==2.0.5
alembic==0.8.8.dev0
amqp==1.4.9
anyjson==0.3.3
apsw==3.13.0.post1
argcomplete==1.7.0
argh==0.26.2
attrs==16.3.0
Babel==2.3.4
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.4.1
billiard==3.3.0.23
biplist==1.0.1
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
bs4==0.0.1
capstone==3.0.4
celery==3.1.23
certifi==2016.2.28
characteristic==14.3.0
chardet==2.3.0
Cheetah==2.4.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20161123
clamd==1.0.1
clearbit==0.1.4
click==6.6
cluster==1.3.3
colorama==0.3.7
config==0.3.9
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.3.0.post2
construct==2.5.2
couchdbkit==0.6.5
creepy==1.2
cryptography==1.4
ctypeslib==0.5.6
cycler==0.10.0
d2to1==0.2.12
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.0.10
defusedxml==0.4.1
dicttoxml==1.6.6
dissy==9
distlib==0.2.4
distorm3==3.3.4
Django==1.9.8
django-celery==3.1.17
dnspython==1.14.0
docutils==0.13.1
dominate==2.1.5
easygui==0.96
ecdsa==0.13
Elixir==0.7.1
enum34==1.1.6
esmre==0.3.1
feedparser==5.1.3
file-magic==0.3.0
Flask==0.11.1
flickrapi==2.1.2
FormEncode==1.3.0
frida==9.1.23
funcsigs==1.0.2
fuse-python==0.2.1
future==0.15.2
futures==3.0.5
gdata==2.0.18
GeoIP==1.3.2
geoip2==2.4.2
geojson==1.3.1
gevent==1.1.2
gitdb2==2.0.0
GitPython==2.1.1
google-api-python-client==1.5.5
greenlet==0.4.10
guess-language-spirit==0.5.2
h2==2.4.1
hachoir-core==1.3.3
hachoir-parser==1.3.4
hachoir-regex==1.0.5
hachoir-subfile==0.5.3
halberd==0.2.4
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
icalendar==3.8
idna==2.1
impacket==0.9.15
ipaddr==2.1.11
ipaddress==1.0.17
IPy==0.83
ipython==2.4.1
itsdangerous==0.24
jdcal==1.0
Jinja2==2.8
json2html==1.0.1
jsonpickle==0.9.3
jsonrpclib==0.1.3
keepnote==0.7.8
killerbee==1.0
knockpy==4.0
kombu==3.0.35
linecache2==1.0.0
lxml==3.6.0
M2Crypto==0.24.0
Mako==1.0.6
Markdown==2.6.7
MarkupSafe==0.23
matplotlib==1.5.2rc2
maxminddb==1.2.2
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.17.1
mock==2.0.0
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.7
nassl==0.12
ndg-httpsclient==0.4.2
netaddr==0.7.18
NfSpy==1.0
nltk==3.2.1
numpy==1.12.0b1
oauth2client==3.0.0
oauthlib==2.0.1
olefile==0.42.1
openpyxl==2.3.0
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.0.post20161128115349
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathtools==0.1.2
pbr==1.10.0
pcapy==0.10.8
pdfminer==20140328
pefile==2016.3.28
pexpect==4.2.1
phply==0.9.1
Pillow==3.2.0
piplapis-python==5.1.0
ply==3.9
prettytable==0.7.2
prompt-toolkit==1.0.14
psutil==5.0.0
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.15
PyBluez==0.18
PyChart==1.39
pycrypto==2.6.1
pycryptopp==0.7.1
pycurl==7.43.0
pydasm==1.5
pydns==2.3.6
pydot==1.0.29
pyenchant==1.6.7
PyGithub==1.23.0
Pygments==2.1.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.4.2
pylibemu==0.3.3
pyliblzma==0.5.3
pymongo==3.3.0
pymssql==1.0.2
PyOpenGL==3.1.0
pyOpenSSL==16.2.0
pyotp==2.2.1
pyparsing==2.1.10
pyPdf==1.13
PyPDF2==1.26.0
pyperclip==1.5.27
pyqtgraph==0.10.0
pyregfi==1.0.1.0
pyrit==0.4.0
pyscard==1.9.4
pyserial==3.2.1
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pysqlite==2.7.0
pytest==3.0.5
python-apt==1.1.0b5
python-dateutil==2.5.3
python-debian==0.1.29
python-debianbts==2.6.1
python-editor==0.4
python-instagram==1.3.2
python-ldap==2.4.28
python-Levenshtein==0.12.0
python-lzo==1.8
python-magic==0.4.13
python-ntlm==1.1.0
python-openid==2.2.5
python-pam==1.8.2
python-stdnum==1.5
python-Wappalyzer==0.2.2
python-whois==0.6.2
pytidylib==0.2.4
pytz==2016.6.1
pyusb==1.0.0b2
PyWebDAV==0.9.8
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
readline==6.2.4.1
reportbug==6.6.6
reportlab==3.3.0
requests==2.10.0
requests-file==1.4
requests-oauthlib==0.7.0
requests-toolbelt==0.7.0
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
rpm-python==4.12.0.2
rsa==3.4.2
ruamel.ordereddict==0.4.9
scapy===unknown.version
scgi==1.13
scipy==0.18.1
service-identity==16.0.0
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smmap2==2.0.1
smoke-zephyr==1.0.2
SOAPpy==0.12.22
socketpool==0.5.3
SQLAlchemy==1.0.15
sshtunnel==0.1.2
stopit==1.1.0
tblib==1.3.0
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
tldextract==2.0.1
tornado==4.4.2
tqdm==4.7.6
traceback2==1.4.0
tweepy==3.5.0
Twisted==16.2.0
tzlocal==1.3
unittest2==1.1.0
uritemplate==0.6
urlgrabber==3.10.1
urllib3==1.19.1
urwid==1.3.1
usnparser==2.0.4
uTidylib==0.3
vatnumber==1.2
vinetto==0.7b0
vobject==0.9.3
vulndb==0.0.19
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webunit==1.3.10
Werkzeug==0.11.11.dev0
wfuzz==0.0.0
Whoosh==2.7.0
wstools==0.4.3
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.5
XlsxWriter==0.9.3
xlwt==0.7.5
xmlbuilder==1.0
Yapsy==1.11.223
yara-python==3.4.0.0
yum-metadata-parser==1.1.4
zenmap==7.40
zim==0.65
zope.interface==4.3.2
ZSI==2.1a1

#### Device iOS Version
9.3.1

**Comment by marco-lancini** [comment]
is the agent on the foreground?

**Comment by null0x4d5a** [comment]
yes agent 1.0.3

**Comment by marco-lancini** [comment]
can you please enable `DEBUG` logging and post the output?

**Comment by null0x4d5a** [comment]
![4](https://cloud.githubusercontent.com/assets/14013208/26348418/5247909c-3fca-11e7-9ab8-62b08ebb8f97.png)
![5](https://cloud.githubusercontent.com/assets/14013208/26348422/524dcd86-3fca-11e7-9fb0-67cad17474fb.png)
![1](https://cloud.githubusercontent.com/assets/14013208/26348419/5249e54a-3fca-11e7-9ee4-9ec2d2f80946.png)
![2](https://cloud.githubusercontent.com/assets/14013208/26348420/524ca9d8-3fca-11e7-845c-ca6c957370d4.png)
![3](https://cloud.githubusercontent.com/assets/14013208/26348421/524ce5ec-3fca-11e7-9073-efe523d83e92.png)

**Comment by null0x4d5a** [comment]
Sorry, the screenshots are not in order

**Comment by marco-lancini** [comment]
seems like the agent on the device is not on the foreground...

**Comment by null0x4d5a** [comment]
Agent was on foreground and working

**Comment by null0x4d5a** [comment]
I tried same, but it's still stuck after run command and not able to fetch any output from modules

**Comment by marco-lancini** [comment]
In 2 different screenshots you are using 2 different IP addresses for the device.

In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files (starting from when you type `python needle.py`) to this thread and we can assist further. 

Please don't post screenshots but copy-paste from console

**Comment by null0x4d5a** [comment]
Apart from console output, Is there any specific location for log file or
debug information stored ?

**Comment by marco-lancini** [comment]
Nope

**Comment by b0ngmaster** [comment]
Hi marco, Im having the same problem, please see the full console output below, the needle agent is in the foreground, v1.0.4 and shows the connection from kali. thanks

root@kali:/usr/share/needle/needle# python needle.py 

             __   _ _______ _______ ______         _______
             | \  | |______ |______ |     \ |      |______
             |  \_| |______ |______ |_____/ |_____ |______
        
                   Needle v1.2.0 [mwr.to/needle]                  
  [MWR InfoSecurity (@MWRLabs) - Marco Lancini (@LanciniMarco)]   

[needle] > show options

  Name                      Current Value         Required  Description
  ------------------------  -------------         --------  -----------
  AGENT_PORT                4444                  yes       Port on which the Needle Agent is listening
  APP                                             no        Bundle ID of the target application (e.g., com.example.app). Leave empty to launch wizard
  DEBUG                     False                 yes       Enable debugging output
  IP                        127.0.0.1             yes       IP address of the testing device (set to localhost to use USB)
  OUTPUT_FOLDER             /root/.needle/output  yes       Full path of the output folder, where to store the output of the modules
  PASSWORD                  ********              yes       SSH Password of the testing device
  PORT                      2222                  yes       Port of the SSH agent on the testing device (needs to be != 22 to use USB)
  PUB_KEY_AUTH              True                  yes       Use public key auth to authenticate to the device. Key must be present in the ssh-agent if a passphrase is used
  SAVE_HISTORY              True                  yes       Persists command history across sessions
  SKIP_OUTPUT_FOLDER_CHECK  False                 no        Skip the check that ensures the output folder does not already contain other files. It will automatically overwrite any file
  USERNAME                  root                  yes       SSH Username of the testing device
  VERBOSE                   True                  yes       Enable verbose output

[needle] > set IP 192.168.43.22
IP => 192.168.43.22
[needle] > set PORT 22
PORT => 22
[needle] > set PASSWORD alpine
PASSWORD => ********
[needle] > set DEBUG True
DEBUG => True
[needle] > set VERBOSE True
VERBOSE => True
[needle] > use storage/data/keychain_dump
[needle][keychain_dump] > show options

  Name    Current Value         Required  Description
  ------  -------------         --------  -----------
  FILTER                        no        Filter to apply when analyzing. If empty, the entire keychain file will be shown
  OUTPUT  /root/.needle/output  yes       Full path of the output folder

[needle][keychain_dump] > run
[D] Setup local output folder: /root/.needle/output
[?] Attention! The folder chosen to store local output is not empty: /root/.needle/output
[?] Do you want to back it up first?
[?] Y: the content will be archived in a different location, then the folder will be emptied
[?] N: no action will be taken (destination files might be overwritten in case of filename clash)
[y/n]: n
[D] Setting up issue's database...
[D] [DB] QUERY: CREATE TABLE IF NOT EXISTS issues (app TEXT, module TEXT, name TEXT, content TEXT, confidence TEXT, outfile TEXT)
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] [AGENT] Connecting to agent (192.168.43.22:4444)...
[+] [AGENT] Successfully connected to agent (192.168.43.22:4444)...
[D] [AGENT] Executing command: os_version
[D] [AGENT] Parsing result (are you sure the agent is in the foreground?)

**Comment by marco-lancini** [comment]
Hi @b0ngmaster: can you connect the device to Xcode and analyse the syslog?

**Comment by b0ngmaster** [comment]
i have no mac :( 
are there issues with 32bit devices? this is an ipad 32bit. 
Thanks

**Comment by marco-lancini** [comment]
yeah 32bit devices are not fully supported...
