### ISSUE TITLE
Not able to install Needle agent

### ISSUE THREAD

**Issue by pentagramz** [mwrlabs/needle#178]
### Expected behaviour
Tell us what should happen.

Link not accessible

http://mobiletools.mwrinfosecurity.com/cydia/

https://github.com/mwrlabs/needle/wiki/Installation-Guide

### Actual behaviour
Tell us what happens instead.

 Not able to add repo

### Steps to reproduce
1.  
2.
3.

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

#### Needle Version

- Framework (on your machine): 
- Agent (on your device):

#### Device iOS Version
10.2

**Comment by marco-lancini** [comment]
Hi @pentagramz, can you please double check?
I can confirm the repo is up and running.

**Comment by pentagramz** [comment]
![repo](https://user-images.githubusercontent.com/7072014/27198784-458080e8-5231-11e7-8d6d-651f39a48fd9.PNG)


Am I doing right?

Added repo in cydia mobile ..its not getting added
please help

**Comment by marco-lancini** [comment]
Getting a 404 if you try to hit `http://mobiletools.mwrinfosecurity.com/cydia/` with your browser is intended behaviour. Cydia will instead use that endpoint to fetch a bunch of components needed to install the app (e.g., `NeedleAgent.deb`, `CydiaIcon.png`, etc.)

Following the instructions listed in the Installation Guide (https://github.com/mwrlabs/needle/wiki/Installation-Guide#install-the-needle-agent) it's enough.
If your device can't contact the repo, try to check your network connection.

**Comment by pentagramz** [comment]
![img_0012](https://user-images.githubusercontent.com/7072014/27260334-0892bff8-5447-11e7-8095-a804c8b3b65f.PNG)

Hi Marco , I am trying to install in ios 10.2 jailbroken.
I am not able to see the icon, the needle agent not installed.
Any pointers?

**Comment by marco-lancini** [comment]
Hi @pentagramz, as you can see from the error you posted, you run out of space on your device

> No space left on device

You won't be able to install anything until you free up some space.
Closing this as this is not related to Needle

**Comment by Hellowman** [comment]
Hello @marco-lancini I have the same problem. I can't add the repository to the Cydia Sources http://mobiletools.mwrinfosecurity.com/cydia/
My network connection is ok.
And there are no results search for NeedleAgent:
![IMG_6995](https://user-images.githubusercontent.com/11087759/84407654-cc4a5100-ac13-11ea-8b6b-aebeef6f7391.PNG)
![IMG_6994](https://user-images.githubusercontent.com/11087759/84407677-d409f580-ac13-11ea-8550-0379d870604c.PNG)
![IMG_6993](https://user-images.githubusercontent.com/11087759/84407705-de2bf400-ac13-11ea-8e45-1eb58c1890f7.PNG)
