### ISSUE TITLE
Static\Code_Check not returning any results

### ISSUE THREAD

**Issue by kahashi** [mwrlabs/needle#192]
## Issue
When I run the static/code_checks modules, I get the following:

[needle][code_checks] > run
[V] Static Module, connection not needed...
[*] Checking for insecure functions...
[needle][code_checks] > 

### Expected behaviour
A static code analysis should run against my IPA file and provide me some kind of results (whether something was found or not)

### Actual behaviour
Nothing

### Steps to reproduce
1. use static/code_checks
2. set PRIMARY_FOLDER /Users/user/test_needle/my_IPA
3. run

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

## Environment
[needle][code_checks] > run
[V] Static Module, connection not needed...
[*] Computing diff...
[D] [LOCAL CMD] Local Command: diff -qr /Users/user/test_needle/my_IPA /Users/user/test_needle/DS_Secondary
[*] Checking for insecure functions...
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSFile' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'writeToFile' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'applicationWillResignActive' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'applicationWillTerminate' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'applicationDidEnterBackground' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'strcat' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'strcpy' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'strncat' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'strncpy' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'sprintf' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'vsprintf' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'fopen' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'gets(' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'chmod' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'stat(' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'mktemp' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'http://' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSURL' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'URL' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'writeToUrl' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSURLConnection' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'CFStream' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSStreamin' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'base64' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'MD5' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSLog *([^"']*)' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'stringWithFormat[^"']*(,|])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'initWithFormat[^"']*(,|\])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'appendFormat[^"']*(,|\])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'informativeTextWithFormat[^"']*(,|\])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'predicateWithFormat[^"']*(,|\])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'stringByAppendingFormat[^"']*(,|\])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'alertWithMessageText[^"']*(,|\])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSException +format[^"']*(,|\])' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSRunAlertPanel' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSUserDefaults' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSDataWritingFileProtectionNone' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSDataWritingFileProtectionComplete' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSDataWritingFileProtectionCompleteUnlessOpen' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSDataWritingFileProtectionCompleteUntilFirstUserAuthentication' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSFileProtectionKey' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSFileProtectionNone' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSFileProtectionComplete' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSFileProtectionCompleteUnlessOpen' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSFileProtectionCompleteUntilFirstUserAuthentication' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} '://' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'openUrl' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'handleOpenURL' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'UIWebView' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'loadRequest' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'loadHTMLString' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'shouldStartLoadWithRequest' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'stringByEvaluatingJavaScriptFromString' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'baseURL' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSHTTPCookieAcceptPolicyNever' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSHTTPCookieAcceptPolicyOnlyFromMainDocumentDomain' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'canAuthenticateAgainstProtectionSpace' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'setAllowsAnyHTTPSCertificate' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'didReceiveAuthenticationChallenge' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'willSendRequestForAuthenticationChallenge' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'continueWithoutCredentialForAuthenticationChallenge' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kCFStreamSSLAllowsExpiredCertificates' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kCFStreamSSLAllowsExpiredRoots' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kCFStreamSSLAllowsAnyRoot' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kCFStreamSSLValidatesCertificateChain' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kCFStreamPropertySSLSettings' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kCFStreamSSLPeerName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kSecTrustOptionAllowExpired' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kSecTrustOptionAllowExpiredRoot' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kSecTrustOptionImplicitAnchors' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSStreamSocketSecurityLevelTLSv1' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSStreamSocketSecurityLevelKey' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'autocorrectionType' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'UITextAutocorrectionNo' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'SQL' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'sqlite' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'table' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'cursor' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'sqlite3_prepare(' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'sqlcipher' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'willCacheResponse' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'password' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'NSLog' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'foundExternalEntityDeclarationWithName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'foundAttributeDeclarationWithName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'foundElementDeclarationWithName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'foundInternalEntityDeclarationWithName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'foundUnparsedEntityDeclarationWithName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'foundNotationDeclarationWithName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'UIPasteboardNameGeneral' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'UIPasteboardNameFind' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'pasteboardWithName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'pasteboardWithUniqueName' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'SecItemAdd' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'SecItemUpdate' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'SecItemCopyMatching' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'kSecASttr' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[D] [LOCAL CMD] Local Command: grep -irn -H --include="*.m" --exclude-dir=.{git,hg,svn} 'SFHFKkey' /Users/user/test_needle/my_IPA | awk -F":" '{print $1}'| sort | uniq
[needle][code_checks] > 

#### Needle Version
     Needle v1.3.2 [mwr.to/needle]  
                
- Framework (on your machine): 

- Agent (on your device):
needle v.1.0.5

#### Workstation Operating System
Mac Sierra
10.12.4

#### Python Version
Python 2.7.13

#### Python Packages (`pip freeze`)
Last login: Wed Aug 30 15:10:51 on ttys000
machineID:test_needle asyfa$ pip freeze
asn1crypto==0.22.0
backports-abc==0.5
bcrypt==3.1.3
biplist==1.0.2
blinker==1.4
certifi==2017.7.27.1
cffi==1.10.0
chardet==2.1.1
cluster==1.1.1b3
ConfigArgParse==0.12.0
configparser==3.5.0
cryptography==2.0.3
darts.util.lru==0.5
Django==1.11.4
enum34==1.1.6
esmre==0.3.1
Flask==0.10.1
futures==2.1.5
gitdb2==2.0.2
GitPython==2.1.3
guess-language==0.2
halberd==0.2.4
hpack==3.0.0
html2text==2016.9.19
idna==2.5
ipaddress==1.0.18
itsdangerous==0.24
Jinja2==2.7.3
lizard==1.12.11
lxml==3.8.0
Markdown==2.6.1
MarkupSafe==1.0
mitmproxy==0.13
msgpack-python==0.4.4
ndg-httpsclient==0.3.3
netlib==0.13.1
nltk==3.0.1
olefile==0.44
paramiko==2.2.1
passlib==1.7.1
pdfkit==0.6.1
pdfminer==20140328
phply==0.9.1
Pillow==4.2.1
ply==3.10
psutil==2.2.1
pyasn1==0.1.9
pybloomfiltermmap==0.3.14
pyClamd==0.3.15
pycparser==2.18
PyGithub==1.21.0
PyNaCl==1.1.2
pyOpenSSL==17.2.0
pyparsing==2.2.0
pyperclip==1.5.27
pysolr==3.6.0
python-ntlm==1.0.1
pytz==2017.2
PyYAML==3.12
requests==2.18.3
rsa==3.4.2
ruamel.ordereddict==0.4.8
scapy-real==2.2.0.dev0
singledispatch==3.4.0.3
six==1.10.0
smmap2==2.0.3
sshtunnel==0.1.2
tblib==0.2.0
termcolor==1.1.0
tldextract==1.7.2
tornado==4.5.2
urllib3==1.22
urwid==1.3.1
vulndb==0.0.19
watson-developer-cloud==0.26.1
Werkzeug==0.12.2
xdot==0.6

#### Device iOS Version
10.1.1

**Comment by marco-lancini** [comment]
Hi, this module requires the source code of your target app, not the IPA.
