### ISSUE TITLE
Issue with biplist

### ISSUE THREAD

**Issue by 0xff7** [mwrlabs/needle#193]
when trying to run needle.py in latest version of Sierra I get the following output

`$ python ./needle.py
Traceback (most recent call last):
  File "./needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/tim/needle/needle/core/framework/cli.py", line 8, in <module>
    from ..utils.printer import Colors, Printer
  File "/Users/tim/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils
  File "/Users/tim/needle/needle/core/utils/utils.py", line 6, in <module>
    import biplist
ImportError: No module named biplist`

any ideas?

**Comment by marco-lancini** [comment]
please read the installation guide: https://github.com/mwrlabs/needle/wiki/Installation-Guide#os-x

**Comment by allRiceOnMe** [comment]
Ok, I just want to mention that I had similar issues using the latest version of High Sierra.

My solution to this:

```
$ sudo easy_install-2.7 readline paramiko sshtunnel frida biplist
```

Now running needle with following command should work:

```
$ python2 needle.py
```

Note that running `$ python needle.py` still doesn't work (Error message `IOError: [Errno 2] No such file or directory`).

I don't have an explanation for this. Maybe you have ...
