### ISSUE TITLE
NeedleAgent not visible after Installation 

### ISSUE THREAD

**Issue by bugzapperini** [mwrlabs/needle#194]
### Expected behaviour
NeedleAgent should be visible after Installation in jailbroken iPhone. 

### Actual behaviour
I have iphone 6s with iOS 9.3.2. 

### Steps to reproduce
1.I've downloaded NeedleAgent.deb file from latest release.  

2. I installed it using Filza File Manager as well as MobileTerminal. 
3. After respring it is not visible in list of apps nor in settings. 
4. However it is visible in Cydia listing. 

I'm not sure if iOS 9.3.2 actually require NeedleAgent

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```
NA

## Environment
NA
#### Needle Version

- Framework (on your machine): NA
- Agent (on your device): 1.0.5

#### Workstation Operating System
NA
#### Python Version
NA
#### Python Packages (`pip freeze`)
NNA
#### Device iOS Version
9.3.2 (iPhone 6s)

**Comment by marco-lancini** [comment]
Hi @bugzapperini, you don't have to manually install the deb file to install the agent, you can install it from Cydia: https://github.com/mwrlabs/needle/wiki/Installation-Guide#install-the-needle-agent
