### ISSUE TITLE
getting these errors help?

### ISSUE THREAD

**Issue by 0xff7** [mwrlabs/needle#195]
When running ``python needle.py`` I get the following errors
`$ python needle.py
Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli`

  `File "/Users/tim/needle/needle/core/framework/cli.py", line 8, in <module>
    from ..utils.printer import Colors, Printer`

  `File "/Users/tim/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils`

  `File "/Users/tim/needle/needle/core/utils/utils.py", line 6, in <module>
    import biplist
ImportError: No module named biplist`

I have installed all dependencies and I'm running macOS Sierra 10.12.6

**Comment by marco-lancini** [comment]
Duplicate #193
