### ISSUE TITLE
Exception: Support for iOS < 8 not yet implemented.

### ISSUE THREAD

**Issue by ankushgoel27** [mwrlabs/needle#2]
Hi,

I am using IOS 9.3.3 jailbroken device. i am getting an error saying that "Exception: Support for iOS < 8 not yet implemented." what does this mean. Does it mean that i will need to use a device with IOS less than 8?

**Comment by marco-lancini** [comment]
If you look at the `README` file, you will see that:

> iOS8 is currently supported (testing on iOS9 is currently in progress)

**Comment by ankushgoel27** [comment]
waiting eagerly for your ios9 support. This tools is amazing. thanks :)

**Comment by throwawaynow** [comment]
Currently having same issue with Needle v0.1.1 [mwr.to/needle]

**Comment by marco-lancini** [comment]
In order to debug this issue, we require more information.

Ensure `VERBOSE` and `DEBUG` mode are enabled, this will provide us with more detailed needle logs:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

Once you have this information, please attach the log files to this thread and we can assist further.

**Comment by throwawaynow** [comment]
Thank you for the quick reply:
------------------------------------------
[needle][strings] > run
[D] Setup local output folder: /Users/xxx/.needle/output
[*] Checking connection with device...
[+] Already connected to: x.x.x.x
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: mkdir /var/root/needle/
[+] Target app: xxx
[*] Retrieving app's metadata...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -f /private/var/installd/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
-------------------------------------------
Traceback (most recent call last):
  File "/Users/xxx/needle/needle/core/framework/module.py", line 112, in do_run
    pre = self.module_pre()
  File "/Users/xxx/needle/needle/core/framework/module.py", line 144, in module_pre
    if self.app_check() is None: return None
  File "/Users/xxx/needle/needle/core/framework/framework.py", line 692, in app_check
    self.APP_METADATA = Framework.APP_METADATA = self.device.app.get_metadata(app)
  File "/Users/xxx/needle/needle/core/device/app.py", line 19, in get_metadata
    self._device._list_apps()
  File "/Users/xxx/needle/needle/core/device/device.py", line 199, in _list_apps
    else: list_iOS_7()
  File "/Users/xxx/needle/needle/core/device/device.py", line 185, in list_iOS_7
    raise Exception('Support for iOS < 8 not yet implemented')
Exception: Support for iOS < 8 not yet implemented
------------------------------------------------------------
[!] Exception: Support for iOS < 8 not yet implemented.

**Comment by marco-lancini** [comment]
what iOS version is your device running?

**Comment by throwawaynow** [comment]
iOS 9.2 (with pangu), I had some issues with the installation process so maybe I should reinstall and try again.

**Comment by marco-lancini** [comment]
reinstall what?

**Comment by marco-lancini** [comment]
close due to inactivity
