### ISSUE TITLE
Adding Needle-Agent as per documentation

### ISSUE THREAD

**Issue by subrosaassociates** [mwrlabs/needle#205]
## Issue
The Repo no-longer exists at http://mobiletools.mwrinfosecurity.com/cydia/ for ios
### Expected behaviour
if the documentation is correct, it should be there, to be added to cydia sources, to be searched, downloaded and installed

### Actual behaviour
it doesnt exist

### Steps to reproduce
1.follow the documentation to acquiring the agent via cydia ( https://github.com/mwrlabs/needle/wiki/Installation-Guide)

any help is good !, i've used it before, i really want to use it again - nice work.

**Comment by subrosaassociates** [comment]
I got it installed by pulling the mobiletools site (hosted on here, and hosting it locally)
https://github.com/mwrlabs/mobiletools

**Comment by marco-lancini** [comment]
I can ensure the repo is still available at the URL pointed in the installation guide.
@HenryHoggard I suggest you close this issue

**Comment by subrosaassociates** [comment]
<img width="1187" alt="screen shot 2018-02-20 at 22 00 47" src="https://user-images.githubusercontent.com/34861344/36451616-8eba2436-1689-11e8-955d-8aa3966c3b79.png">
<img width="1148" alt="screen shot 2018-02-20 at 22 00 37" src="https://user-images.githubusercontent.com/34861344/36451617-8ed45a18-1689-11e8-89ba-8580a4c3c31f.png">

**Comment by marco-lancini** [comment]
@subrosaassociates: this is intended behaviour. The repo is not intended to be parsed by web browsers but by Cydia

**Comment by subrosaassociates** [comment]
ah, i only viewed it in the browser when it failed in cydia ... it doesnt matter to me now I pulled the site and hosted it locally - from my journey, i assumed the cydia site was down as it exhibited all the signs of being removed (at the time) - that's not to say it's not my fault, but it didnt look like it. 

Needles working fine for me, having hosted it locally and added a local repo :) thanks for the great tool.

**Comment by marco-lancini** [comment]
No worries! :)
Happy it is helpful for you
