### ISSUE TITLE
[list_App] modules error

### ISSUE THREAD

**Issue by swaroopsy** [mwrlabs/needle#21]
### Expected behaviour
This module is supposed to list all installed apps.

### Actual behaviour
Instead of listing apps, its giving error message as 'ExpatError: unclosed token: line 4910, column 23]

### Steps to reproduce
1. Select the module list_apps for connection iOS 9.0.2
2. After running the module, it will give error as attached screenshot.

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```
![needle_error_listing_apps](https://cloud.githubusercontent.com/assets/9929997/18606296/799a6580-7cc9-11e6-91e5-10da3e0117fe.png)

#### Device iOS Version
iOS 9.0.2

**Comment by marco-lancini** [comment]
Hi @swaroopsy , could you please enable also debug mode and post the output?

**Comment by marco-lancini** [comment]
Hi @swaroopsy, any update on this?

**Comment by marco-lancini** [comment]
close for inactivity
