### ISSUE TITLE
Could not find the cydia repository to add needle agent

### ISSUE THREAD

**Issue by kaleemshaik7867** [mwrlabs/needle#244]
## Issue

Hi, While trying to add new resource getting error saying "page does not exist" 

http://mobiletools.mwrinfosecurity.com/cydia/

![image](https://user-images.githubusercontent.com/7692857/38015934-7dd818ba-327e-11e8-940f-1768ea4b9292.png)

**Comment by HenryHoggard** [comment]
Thanks - we're aware, Github pages is where the repo is hosted, Github changed how GH pages works and has messed up the Cydia repo, we are just working on getting new hosting.

**Comment by HenryHoggard** [comment]
In the meantime you can install it manually.

**Comment by marco-lancini** [comment]
Close due to inactivity
