### ISSUE TITLE
Unable to run Needle

### ISSUE THREAD

**Issue by pentagramz** [mwrlabs/needle#246]
## Issue
Unable to run Needle
### Expected behaviour
Tell us what should happen.
Console should run
### Actual behaviour
Tell us what happens instead.
error 
### Steps to reproduce
1.
2.
3.

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

#### Needle Version

- Framework (on your machine): 
- Agent (on your device):

#### Workstation Operating System
Mac OSX ElCapitan
#### Device iOS Version
9.3.5 ipad mini
![screen shot 2018-04-07 at 7 50 30 pm](https://user-images.githubusercontent.com/7072014/38455991-06f04f20-3a9d-11e8-87eb-0680571ae0c6.png)

**Comment by meetinthemiddle-be** [comment]
How does python needle.py treat you instead of needle-cli.py?

**Comment by pentagramz** [comment]
Solved it both working fine now
