### ISSUE TITLE
Mac Terminal gets hung will executing commands on the device

### ISSUE THREAD

**Issue by samlframework** [mwrlabs/needle#250]
## Issue
Terminal gets hung and can't execute further commands.

### Expected behaviour
Command should execute and should give us the result and the terminal shouldn't hung.

### Actual behaviour
Terminal gets hung, no response :(

### Steps to reproduce
1. Start the needle agent on the phone and make sure its listening on the proper port.
2. From the mac machine, connect to the agent and run commands like below:
[needle] > use dynamic/monitor/pasteboard
[needle][pasteboard] > run
[D] Setting up issues database...
[D] [DB] QUERY: CREATE TABLE IF NOT EXISTS issues (app TEXT, module TEXT, name TEXT, content TEXT, confidence TEXT, outfile TEXT)
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] [AGENT] Connecting to agent (10.13.77.3:4443)...
[+] [AGENT] Successfully connected to agent (10.13.77.3:4443)...
[D] [AGENT] Executing command: os_version
[V] [SSH] Connecting (10.13.77.3:22)...
[+] [SSH] Connected (10.13.77.3:22)
[D] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[D] [AGENT] Executing command: os_version
[*] Target app not selected. Launching wizard...
[D] [AGENT] Executing command: list_apps
[+] Apps found:
		0 - com.apple.MobileAddressBook
		1 - com.apple.Passbook
		2 - com.apple.GameController
		3 - com.apple.WebContentFilter.remoteUI.WebContentAnalysisUI
		4 - com.apple.iBooks
		5 - com.apple.WebViewService
		6 - com.apple.InCallService
		7 - com.apple.Preferences
		8 - com.apple.PhotosViewService
		9 - com.apple.facetime
                77 -  XX.XX.XX.XX.XX

[>][QUESTION] Please select a number: 77
[+] Target app: XX.XX.XX.XX.XX
[*] Retrieving app's metadata...
[D] Copying the plist to temp: /private/var/mobile/Containers/Bundle/Application/4FAFE338-DFD0-4DF5-9630-7118695328D8/TESTV2.app/Info.plist -> /Users/rock1/.needle/tmp/plist
[*] Pulling: /private/var/mobile/Containers/Bundle/Application/4FAFE338-DFD0-4DF5-9630-7118695328D8/TESTV2.app/Info.plist -> /Users/rock1/.needle/tmp/plist
[D] Downloading: "/private/var/mobile/Containers/Bundle/Application/4FAFE338-DFD0-4DF5-9630-7118695328D8/TESTV2.app/Info.plist" -> /Users/rock1/.needle/tmp/plist
[D] [LOCAL CMD] Local Command: sshpass -p "*****" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 22 root@10.13.77.3:"/private/var/mobile/Containers/Bundle/Application/4FAFE338-DFD0-4DF5-9630-7118695328D8/TESTV2.app/Info.plist" /Users/rock1/.needle/tmp/plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/mobile/Containers/Bundle/Application/4FAFE338-DFD0-4DF5-9630-7118695328D8/TESTV2.app/TESTV2
[!] sh: lipo: command not found

[V] [SSH] Disconnecting...
[V] [AGENT] Disconnecting from agent...
[?] Resetting connection to device...
[V] [AGENT] Connecting to agent (10.13.77.3:4443)...
[+] [AGENT] Successfully connected to agent (10.13.77.3:4443)...
[D] [AGENT] Executing command: os_version

### needle error logs
Verbose and debug mode are enabled, after above the terminal just freezes and can't execute any commands further.
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True

I've set the VERBOSE and DEBUG mode, the terminal gets hung..can't proceed with further commands
```

#### Needle Version

- Framework (on your machine): v1.3.2
- Agent (on your device): v.1.0.5

#### Python Version
Python 2.7.10

#### Python Packages (`pip freeze`)
altgraph==0.10.2
backports-abc==0.5
bdist-mpkg==0.5.0
bonjour-py==0.3
certifi==2017.4.17
configparser==3.5.0
Django==1.11.1
EasyProcess==0.2.3
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
py2app==0.7.3
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
PyVirtualDisplay==0.2.1
scipy==0.13.0b1
selenium==3.11.0
singledispatch==3.4.0.3
six==1.4.1
tornado==4.5.1
virtualenv==15.2.0
wget==3.2
xattr==0.6.4
zope.interface==4.1.1

#### Device iOS Version
Rooted i-phone 6 Gold,version - 8.4(12H143)

**Comment by marco-lancini** [comment]
Hi, from the error you can see that:

> [!] sh: lipo: command not found

Please follow the [Installation Guide](https://github.com/mwrlabs/needle/wiki/Installation-Guide) and install all the dependencies before trying to run needle
