### ISSUE TITLE
Kali

### ISSUE THREAD

**Issue by garyddison** [mwrlabs/needle#254]
## Issue
When trying to run the needle python script after installing all dependencies successfully I get the following error
### Expected behaviour
Console should load

### Actual behaviour
Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli
  File "/tools/needle/needle/core/framework/cli.py", line 8, in <module>
    from ..utils.printer import Colors, Printer
  File "/tools/needle/needle/core/utils/printer.py", line 4, in <module>
    from utils import Utils
  File "/tools/needle/needle/core/utils/utils.py", line 6, in <module>
    import biplist
ImportError: No module named biplist

### Steps to reproduce
1. python needle.py

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

#### Needle Version
1.0.5
- Framework (on your machine): 
- Agent (on your device):

#### Workstation Operating System
Linux KALI-2016-2 4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux
#### Python Version
Python 2.7.15
#### Python Packages (`pip freeze`)
AdvancedHTTPServer==2.0.11
alembic==0.9.7.dev0
altgraph==0.15
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.24.0
attrs==17.3.0
Automat==0.6.0
basemap==1.0.7
bcrypt==3.1.4
binwalk==2.1.1
biplist==1.0.3
blinker==1.4
boltons==18.0.0
Brlapi==0.6.7
Brotli==1.0.4
cement==2.6.2
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
chrome-gnome-shell==0.0.0
click==6.7
colorama==0.3.7
constantly==15.1.0
construct==2.8.16
crackmapexec==3.1.4
crcelk==1.1
cryptography==2.2.2
cssutils==1.0.2
cupshelpers==1.0
cycler==0.10.0
debtags==2.1
decorator==4.3.0
dnspython==1.15.0
docutils==0.14
docxtpl==0.4.7
-e git+https://github.com/droope/droopescan.git@ad1ff070a3c9f334410b638fee93d0b6f0be0730#egg=droopescan
dropbox==8.5.1
EasyProcess==0.2.3
ecdsa==0.13
EditorConfig==0.12.2
email-validator==1.0.3
feedparser==5.2.1
Flask==1.0.2
Forensic1394==0.1
frida==11.0.13
future==0.16.0
futures==3.1.1
fuzzywuzzy==0.16.0
geoip2==2.9.0
geojson==2.4.0
gevent==1.2.2
graphene==2.0.1
graphene-sqlalchemy==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
greenlet==0.4.13
h2==3.0.1
hashID==3.1.4
hpack==3.0.0
html2text==2018.1.9
httplib2==0.9.2
hyperframe==4.0.1
hyperlink==17.3.1
icalendar==4.0.0
idna==2.6
impacket==0.9.15
incremental==17.5.0
iptools==0.6.1
iso8601==0.1.11
itsdangerous==0.24
Jinja2==2.10
jsbeautifier==1.6.4
jsonschema==2.6.0
kaitaistruct==0.8
keyring==10.5.1
keyrings.alt==3.0
louis==3.5.0
lxml==4.2.1
M2Crypto==0.29.0
macholib==1.9
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.1
maxminddb==1.4.0
mitmproxy==2.0.2
msgpack==0.5.6
mysqlclient==1.3.10
netaddr==0.7.19
netifaces==0.10.6
numpy==1.14.4
odfpy==1.3.6
olefile==0.45.1
paramiko==2.4.0
passlib==1.7.1
pathtools==0.1.2
pefile==2017.11.5
Pillow==4.3.0
pluginbase==0.5
promise==2.1
prompt-toolkit==1.0.15
psycopg2==2.7.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycparser==2.18
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.1
PyDispatcher==2.0.5
Pygments==2.2.0
pygobject==3.28.2
pyinotify==0.9.6
PyInstaller==3.3.1
pyminifier==2.1
pymongo==3.6.0
pymssql==2.1.3
PyNaCl==1.2.1
PyOpenGL==3.1.0
pyOpenSSL==17.2.0
pyotp==2.2.6
pyparsing==2.2.0
pyperclip==1.6.0
pyqtgraph==0.10.0
pyserial==3.4
PySimpleSOAP==1.16.2
pysmbc==1.0.15.6
pystache==0.5.4
pytesseract==0.1.7
python-apt==1.6.1
python-dateutil==2.6.1
python-debian==0.1.32
python-debianbts==2.7.2
python-docx==0.8.6
python-editor==0.4
python-Levenshtein==0.12.0
python-pam==1.8.3
python-qt-binding==0.2.17
pytz==2018.4
PyVirtualDisplay==0.2.1
pyxdg==0.25
PyYAML==3.12
qt4reactor==1.6
rdpy==1.3.2
readline==6.2.4.1
reportbug==7.1.10
requests==2.18.4
requests-file==1.4.2
rsa==3.4.2
ruamel.yaml==0.15.34
Rx==1.6.0
scipy==0.19.1
SecretStorage==2.3.1
selenium==3.8.0
service-identity==17.0.0
simplejson==3.15.0
singledispatch==3.4.0.3
six==1.11.0
smoke-zephyr==1.0.2
sortedcontainers==2.0.4
SQLAlchemy==1.1.11
sshtunnel==0.1.4
termcolor==1.1.0
termineter==0.2.7
tornado==5.0.2
Twisted==17.9.0
typing==3.6.2
tzlocal==1.5.1
unattended-upgrades==0.1
urllib3==1.22
urwid==2.0.1
vboxapi==1.0
watchdog==0.8.3
wcwidth==0.1.7
websocket-client==0.45.0
Werkzeug==0.14.1
xlrd==1.1.0
XlsxWriter==0.9.6
xlutils==2.0.0
xlwt==1.3.0
zlib-wrapper==0.1.3
zope.interface==4.4.3

#### Device iOS Version
10.3.3

**Comment by marco-lancini** [comment]
Hi, from the error you can see that:

> ImportError: No module named biplist

Please follow the [Installation Guide](https://github.com/mwrlabs/needle/wiki/Installation-Guide) and install all the dependencies before trying to run needle
