### ISSUE TITLE
Feature Request for Global Output path

### ISSUE THREAD

**Issue by summitt** [mwrlabs/needle#27]
I'd like to set a global path for all output artifacts instead of having to change it on every module I import. Currently everything goes into ~/.needle/tmp/. 

Maybe this is possible and i missed it in the settings somewhere.

**Comment by marco-lancini** [comment]
Hi @summitt, this is actually a good point! I'll work to fix it asap

**Comment by marco-lancini** [comment]
Hi @summitt, this has now been pushed into `master`. Could you please pull the new version and give it a try? Thanks!

**Comment by summitt** [comment]
Finally got a chance to test it out. Works great! thanks! Also if someone would like to submit modules to be included in the default version of needle; how would suggest they go about that?

**Comment by marco-lancini** [comment]
It would be awesome if you could contribute! :)
Ideally you could fork the repo, apply your changes, and then propose a pull request to the official `develop` branch. Then I'll be able to accept the pull request and merge your changes in the default version of needle
