### ISSUE TITLE
ImportError: No module named paramiko

### ISSUE THREAD

**Issue by turingH** [mwrlabs/needle#3]
Hi，
i meet some problem
i have already done what installation guide told me with a totally new OS X virtual machine.
but, it shows that

python needle.py 
Traceback (most recent call last):
  File "needle.py", line 9, in <module>
    from core.framework import cli
  File "/Users/xxx/needle/needle/core/framework/cli.py", line 9, in <module>
    from framework import Framework, FrameworkException
  File "/Users/xxx/needle/needle/core/framework/framework.py", line 9, in <module>
    from ..device.device import Device
  File "/Users/xxx/needle/needle/core/device/device.py", line 2, in <module>
    import paramiko
ImportError: No module named paramiko

================
sudo -H pip install --upgrade --user paramiko
Password:
Requirement already up-to-date: paramiko in /private/var/root/Library/Python/2.7/lib/python/site-packages
Requirement already up-to-date: cryptography>=1.1 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from paramiko)
Requirement already up-to-date: pyasn1>=0.1.7 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from paramiko)
Requirement already up-to-date: enum34 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: ipaddress in /private/var/root/Library/Python/2.7/lib/python/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: idna>=2.0 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: six>=1.4.1 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: setuptools>=11.3 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: cffi>=1.4.1 in /private/var/root/Library/Python/2.7/lib/python/site-packages (from cryptography>=1.1->paramiko)
Requirement already up-to-date: pycparser in /private/var/root/Library/Python/2.7/lib/python/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko)

**Comment by dpnishant** [comment]
Hi @turingH,

It seems like the `paramiko` module was not found in your python env. Did you trying installing it: `pip install paramiko`?

**Comment by turingH** [comment]
yes， u can see my cmd history.
i used `sudo -H pip install --upgrade --user paramiko`
thank you for replying so quickly :)

**Comment by turingH** [comment]
```shell
bash-3.2# ls -al | grep paramiko
drwxr-xr-x  86 root  wheel      2924 Aug 11 23:13 paramiko
drwxr-xr-x  10 root  wheel       340 Aug 11 23:13 paramiko-2.0.2.dist-info
bash-3.2# pwd
/private/var/root/Library/Python/2.7/lib/python/site-packages

**Comment by dpnishant** [comment]
@turingH Try doing this `sudo -H pip install paramiko --ignore-installed`

**Comment by turingH** [comment]
thank you! it works now! 👍

**Comment by dpnishant** [comment]
you're welcome!

**Comment by MRVov** [comment]
> when I run this code in debian jessie:
> sudo apt-get install paramiko
> E: Unable to locate package paramiko
> please help.

apt-get install python-paramiko

**Comment by sandman4812av** [comment]
what is wrong here ? installed python-paramiko

root@test-VM:/home/test# python3 asd.py
Traceback (most recent call last):
File "asd.py", line 4, in 
import paramiko
ModuleNotFoundError: No module named 'paramiko'

**Comment by kgm021** [comment]
When i try to install paramiko, i end up with "pkg_resources.DistributionNotFound" error, 

[root@gmka ZKCS]# python3 PreReq.py
Traceback (most recent call last):
  File "PreReq.py", line 5, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
[root@gmka ZKCS]# pip install paramiko
Traceback (most recent call last):
  File "/usr/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==9.0.3' distribution was not found and is required by the application
[root@gmka ZKCS]#

Please help.

**Comment by littlev-ampire** [comment]
> 

I just met similar issue in Visual Studio Code and I resolved it by following command line:
python -m pip install paramiko
(run "pip install paramiko' failed to complain can not find pip") 
In Pycharm, it is more easier, just in the package tab, search out paramiko and install it.
