### ISSUE TITLE
Would it be possible to run Needle on the iOS device?

### ISSUE THREAD

**Issue by cclauss** [mwrlabs/needle#4]
Given a jailbroken iOS device and [Pythonista](http://omz-software.com/pythonista), would it be possible to run Needle directly on the iOS device?

**Comment by marco-lancini** [comment]
Hi, may I ask you for what reason?

**Comment by cclauss** [comment]
My thought was that it would be quite useful to run Needle on my iOS devices to see if it could find vulnerabilities in my currently loaded apps.  If Needle found issues, I might seek to remove those apps from my devices and seek out more secure alternatives.
