### ISSUE TITLE
Contribution guide missing

### ISSUE THREAD

**Issue by tghosth** [mwrlabs/needle#45]
Did the contribution guide get deleted?

**Comment by marco-lancini** [comment]
Hi @tghosth, we are currently investigating... after the outage Github experienced yesterday, we are seeing some file missing! :S

**Comment by tghosth** [comment]
related to [this](https://github.com/mwrlabs/needle/commit/7951383809fd0f67414331201e817c81944585ff)?

**Comment by marco-lancini** [comment]
exactly, I re-created them now :)
