### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by z0mbi3** [mwrlabs/needle#5]
I keep getting the following error when trying to connect to the device. idb works correctly.

I found that the permissions for the file needle/libs/usbmuxd/tcprelay.py didn't include execution bit.

    scalpel:~ z$ ls -l /Users/z/devel/needle/needle/libs/usbmuxd/tcprelay.py
    -rw-r--r--  1 z  staff  4184 11 Aug 14:04 tcprelay.py

This fixed it:

     chmod +x needle/libs/usbmuxd/tcprelay.py

**Comment by marco-lancini** [comment]
Hi @z0mbi3, thank you very much for the submission.
This has now been fixed.
