### ISSUE TITLE
Issue with Frida 

### ISSUE THREAD

**Issue by ankushgoel27** [mwrlabs/needle#51]
## Issue
Frida script find class enum method function giving error.
### Expected behaviour
it should look for the methods for the defined classes.
### Actual behaviour
It threw an error saying tuple out of range.

### Steps to reproduce
1.
2.
3.

### needle error logs
Ensure verbose and debug mode are enabled:
```
nkeydle][script_find-class-enum-methods] > set TARGET_CLASS JailMo 
TARGET_CLASS => JailMonkey
[needle][script_find-class-enum-methods] > run
[D] Setup local output folder: /root/.needle/output
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up SSH connection...
[+] Connected to: 192.168.0.6
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: com.westernhealth.whasome
[*] Retrieving app's metadata...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -f /private/var/installd/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] [REMOTE CMD] Remote Command: cp /private/var/installd/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cp /private/var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/Info.plist /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/whasome
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/PlugIns ]; then echo "yes"; else echo "no" ; fi
[*] Setting up local port forwarding to enable communications with the Frida server...
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/opt/needle/needle/core/framework/module.py", line 253, in module_pre
    FridaModule.module_pre(self)
  File "/opt/needle/needle/core/framework/module.py", line 237, in module_pre
    self.device._portforward_frida_start()
  File "/opt/needle/needle/core/device/device.py", line 140, in _portforward_frida_start
    self._frida_server.start()
  File "/usr/local/lib/python2.7/dist-packages/sshtunnel.py", line 1221, in start
    self._create_tunnels()
  File "/usr/local/lib/python2.7/dist-packages/sshtunnel.py", line 1082, in _create_tunnels
    msg = 'Problem setting SSH Forwarder up: {0}'.format(e.args[0])
IndexError: tuple index out of range
------------------------------------------------------------
[!] IndexError: tuple index out of range.
```

## Environment
VMWARE
#### Workstation Operating System
Kali Linux
#### Python Version
2.7
#### Python Packages (`pip freeze`)
2.7
#### Device iOS Version
9.3.3

**Comment by marco-lancini** [comment]
Hi @ankushgoel27, can you please check if Frida has been installed correctly both on your workstation and on your device?

**Comment by ankushgoel27** [comment]
I update frida on my device and now i am getting this error. do i need to run anything else on my machine or device?


[needle] > use hooking/frida/script_enum-classes
[needle][script_enum-classes] > run
[D] Setup local output folder: /root/.needle/output
[*] Checking connection with device...
[V] Connection not present, creating a new instance
[V] Setting up SSH connection...
[+] Connected to: 192.168.0.6
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: mkdir /var/root/needle/
[+] Target app: com.westernhealth.whasome
[*] Retrieving app's metadata...
[D] [REMOTE CMD] Remote Command: if [ -f /var/mobile/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -f /private/var/installd/Library/MobileInstallation/LastLaunchServicesMap.plist ]; then echo "yes"; else echo "no" ; fi
[V] Refreshing list of installed apps...
[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache
[D] [REMOTE CMD] Remote Command: cp /private/var/installd/Library/MobileInstallation/LastLaunchServicesMap.plist /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/LastLaunchServicesMap.plist
[D] [REMOTE CMD] Remote Command: cp /private/var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/Info.plist /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: plutil -convert xml1 /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: cat /var/root/needle/Info.plist
[D] [REMOTE CMD] Remote Command: lipo -info /private/var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/whasome
[D] [REMOTE CMD] Remote Command: if [ -d /private/var/containers/Bundle/Application/E2E45BB2-8A4A-4CB9-A70F-E89419D767F4/whasome.app/PlugIns ]; then echo "yes"; else echo "no" ; fi
[*] Setting up local port forwarding to enable communications with the Frida server...
[D] Connected over Wi-Fi
[*] Launching the app...
[D] [REMOTE CMD] Remote Command: open com.westernhealth.whasome
[V] Retrieving the PID...
[D] [REMOTE CMD] Remote Command: ps ax | grep -i 'whasome.app'
[V] PID found: 1013
[*] Attaching to process: 1013
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/opt/needle/needle/core/framework/module.py", line 271, in module_pre
    self.session = device.attach(pid)
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 96, in attach
    return Session(self._impl.attach(self._pid_of(target)))
ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
------------------------------------------------------------
[!] ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use.
[needle][script_enum-classes] > run
[*] Checking connection with device...
[+] Already connected to: 192.168.0.6
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: com.westernhealth.whasome
[*] Local port forwarding to enable communications with the Frida server already setup
[D] Connected over Wi-Fi
[*] Launching the app...
[D] [REMOTE CMD] Remote Command: open com.westernhealth.whasome
[V] Retrieving the PID...
[D] [REMOTE CMD] Remote Command: ps ax | grep -i 'whasome.app'
[V] PID found: 1013
[*] Attaching to process: 1013
------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/needle/needle/core/framework/module.py", line 111, in do_run
    pre = self.module_pre()
  File "/opt/needle/needle/core/framework/module.py", line 271, in module_pre
    self.session = device.attach(pid)
  File "/usr/local/lib/python2.7/dist-packages/frida/core.py", line 96, in attach
    return Session(self._impl.attach(self._pid_of(target)))
ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
------------------------------------------------------------
[!] ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use.

**Comment by marco-lancini** [comment]
Hi, as stated in the error:

> unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use

you have to be sure that the 2 instances of frida are running the same version

**Comment by ankushgoel27** [comment]
It got solved. I had to upgrade my Linux frida to the latest version by doing pip install frida --upgrade. After that everything is running smoothly.

Thanks a lot for your support :)

**Comment by marco-lancini** [comment]
No worries! :)
