### ISSUE TITLE
cycript issue

### ISSUE THREAD

**Issue by ankushgoel27** [mwrlabs/needle#54]
### Expected behaviour
isa.messages should show all the methods for that class
### Actual behaviour
isa should have a function called messages. isa.messages is not showing anything and the function doesn't exist

### Steps to reproduce
1.
2.
3.

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

#### Workstation Operating System
kali linux 2016.3
#### Python Version
python 2.7
#### Device iOS Version
9.3.3

**Comment by marco-lancini** [comment]
Sorry but this isn't an issue pertaining to Needle, therefore we can't troubleshoot it.
