### ISSUE TITLE
GDB Issue

### ISSUE THREAD

**Issue by ankushgoel27** [mwrlabs/needle#65]
## Issue
Unable to attach to process in IOS 9

needle][heap_dump] > run
[*] Checking connection with device...
[+] Already connected to: 192.168.0.6
[V] Creating temp folder: /var/root/needle/
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/ ]; then echo "yes"; else echo "no" ; fi
[+] Target app: com.snapdeal.ipad
[*] Launching the app...
[D] [REMOTE CMD] Remote Command: open com.snapdeal.ipad
[V] Retrieving the PID...
[D] [REMOTE CMD] Remote Command: ps ax | grep -i 'Snapdeal.app'
[V] PID found: 938
[D] [REMOTE CMD] Remote Command: echo "info mach-regions" > /var/root/needle/gdb_mach
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/gdb_dumps ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/gdb_dumps ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: rm -rf /var/root/needle/gdb_dumps 2> /dev/null
[D] [REMOTE CMD] Remote Command: if [ -d /var/root/needle/gdb_dumps ]; then echo "yes"; else echo "no" ; fi
[D] [REMOTE CMD] Remote Command: mkdir /var/root/needle/gdb_dumps
[*] Enumerating mach regions...
[D] [REMOTE CMD] Remote Command:         gdb --pid="938" --batch --command=/var/root/needle/gdb_mach 2>/dev/null | grep sub-regions | awk '{print $3,$5}' | while read range; do
        echo "mach-regions: $range"
        cmd="dump binary memory /var/root/needle/gdb_dumps/dump`echo $range| awk '{print $1}'`.dmp $range"
        echo "$cmd" >> /var/root/needle/gdb_ranges
        done 
[*] Dumping memory (it might take a while)...
[D] [REMOTE CMD] Remote Command: gdb --pid="938" --batch --command=/var/root/needle/gdb_ranges &>>/dev/null
[V] Checking if we have dumps...
[D] [REMOTE CMD] Remote Command: ls -alR /var/root/needle/gdb_dumps
[!] It was not possible to attach to the process (known issue in iOS9. A Fix is coming soon).

I believe its an issue with GDB in IOS 9. A lot of posts recommend using JDB instead of GDB for IOS 9 and above. 

## Environment
Kali Linux
#### Workstation Operating System
Kali lInux
#### Python Version
Python 2.7
#### Device iOS Version
IOS 9.3.3

**Comment by marco-lancini** [comment]
Hi @ankushgoel27, yes, we are aware of this issue related to gdb.
We are working on finding an alternative...

**Comment by ankushgoel27** [comment]
I am using JDB as an alternative and this functionality in needle will be amazing.

**Comment by marco-lancini** [comment]
Ok, which version of JDB are you using currently? (and where you downloaded it?)
Also, what kind of integration would you like to see?

**Comment by ankushgoel27** [comment]
I apologize. it was LLDB,not JDB. I uploaded debugserver binary on the device and mapped the ports to attach  lldb from my machine to the process. I used this blog - http://versprite.com/og/ios-reverse-engineering-part-one-configuring-lldb/. its showing 404 right now.

**Comment by ankushgoel27** [comment]
http://codedigging.com/blog/2016-04-27-debugging-ios-binaries-with-lldb/ . this is another blog post which is similar

**Comment by marco-lancini** [comment]
Ok, I'll add it to the TODO list! ;)
