### ISSUE TITLE
open_uri

### ISSUE THREAD

**Issue by ankushgoel27** [mwrlabs/needle#66]
Hi,

i have a question about the open_uri module. Can you please guide me more regarding this module and what it is used for?

Thanks,

**Comment by marco-lancini** [comment]
`dynamic/ipc/open_uri` is a quick module that can be used to quickly invoke URI handlers.
Let's say that your target application registered the "`abcd`" protocol.
You then can invoke the app by calling that protocol (e.g., `abcd://something&param1=value1`).

Depending on how the application handles the URL, and the query string, you might be able to invoke other functions and/or extract data from the app
