### ISSUE TITLE
More insightful reporting for the static code analysis

### ISSUE THREAD

**Issue by dhaugh** [mwrlabs/needle#72]
Currently, the static/code_checks module only outputs lines of file with no context around the issue itself. Additional documentation could make it easier for non security minded developers to use the static analysis functionality to assess and improve their own applications.

Example:
password_references - it is insecure to hard code passwords in applications that will be installed on end user devices. Ensure that none of the following lines include hardcoded credentials:

**Comment by marco-lancini** [comment]
@dhaugh thanks for the suggestion, I agree with you as this could be a good enhancement for non security minded developers.

Do you already have a list of descriptions you want to add to the different categories of issues?

**Comment by marco-lancini** [comment]
Hi @dhaugh, any update on this?
