### ISSUE TITLE
Issue in SSH Connection Establishment 

### ISSUE THREAD

**Issue by security-prince** [mwrlabs/needle#73]
I am not able to connect to ssh via needle,whereas when i am connecting via ssh in my local machine i am able to establish a connection with my iphone.
Workstation Details:
iOS 9.0.2(jailbroken)
OS: Kali Linux Rolling edition

Attaching the scenario of my workstation when i am trying to establish connection with my device via ssh
![screenshot from 2016-11-09 14-20-57](https://cloud.githubusercontent.com/assets/5870952/20132375/ae4ac8ea-a688-11e6-8011-8b5c50deb768.png)

![screenshot from 2016-11-09 14-28-42](https://cloud.githubusercontent.com/assets/5870952/20132421/f0f292c2-a688-11e6-87ac-1ce833db2ca6.png)

And also when i am trying to drop a shell its probing some errors i have attached the screenshots for that too
![screenshot from 2016-11-09 14-48-46](https://cloud.githubusercontent.com/assets/5870952/20133013/bd5c61ec-a68b-11e6-8d12-d91a0f5ed8e6.png)

**Comment by marco-lancini** [comment]
Hi, as you can see from the screenshot above, the authentication failed.
Be sure to set your device's password within needele:

```
set PASSWORD <yourpassword>
```

**Comment by security-prince** [comment]
I tried it but all i can see is this :
![screenshot from 2016-11-10 11-44-12](https://cloud.githubusercontent.com/assets/5870952/20166486/343cf2b8-a73b-11e6-9fb9-93574976f232.png)

**Comment by marco-lancini** [comment]
within Needle, you can use the `shell` command to obtain a shell on the device, without having to type `ssh user@device`.

I suggest you to read Needle's documentation before proceeding: https://github.com/mwrlabs/needle/wiki
