### ISSUE TITLE
cannot get the refreshed list of applications

### ISSUE THREAD

**Issue by eranvak** [mwrlabs/needle#74]
## Issue
Hey, i'm trying to execute the binary/strings method on my connected device but the script could not extract the application list from my device. screenshots attachd 
### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Steps to reproduce
1.
2.
3.

### needle error logs
Ensure verbose and debug mode are enabled:
```
[needle] > set VERBOSE True
VERBOSE => True
[needle] > set DEBUG True
DEBUG => True
```

## Environment
kali linux 2016.1
#### Workstation Operating System
linux
#### Python Version
2.7
#### Python Packages (`pip freeze`)
AdvancedHTTPServer==2.0.5
alembic==0.8.8.dev0
anyjson==0.3.3
apkid==0.9.4
argcomplete==1.4.1
argh==0.26.1
attrs==16.2.0
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.2
BeautifulSoup==3.2.1
beautifulsoup4==4.5.1
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
capstone==3.0.4
cement==2.10.2
censys==0.0.5
certifi==2016.2.28
chardet==2.3.0
Cheetah==2.4.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20160717
click==6.6
cluster==1.3.3
colorama==0.3.7
coloredlogs==5.2
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.3.0.post2
construct==2.5.2
couchdbkit==0.6.5
cryptography==1.5.2
cycler==0.10.0
dap==2.2.6.7
darts.util.lru==0.5
decorator==4.0.6
dicttoxml==1.6.6
dissy==9
distorm3==3.3.4
dnslib==0.9.6
dnspython==1.14.0
docutils==0.12
dshield==0.1
Elixir==0.7.1
emailprotectionslib==0.8.2
enum34==1.1.6
esmre==0.3.1
ez-setup==0.9
feedparser==5.1.3
Flask==0.10.1
Flask-Restless==0.17.0
Flask-SQLAlchemy==2.1
FormEncode==1.3.0
frida==8.1.10
funkload==1.16.1
fuse-python==0.2.1
future==0.15.2
futures==3.0.5
GeoIP==1.3.2
geoip2==2.4.0
geojson==1.3.1
gevent==1.1.1
gitdb2==2.0.0
gitem==0.5.0
GitPython==2.0.9
graphviz==0.5.1
greenlet==0.4.10
guess-language-spirit==0.5.2
h2==2.4.1
halberd==0.2.4
hpack==2.3.0
html2text==2016.5.29
html5lib==0.999
http-parser==0.8.3
httplib2==0.9.1
httpretty==0.8.14
humanfriendly==2.1
hyperframe==4.0.1
icalendar==3.8
idna==2.1
impacket==0.9.15
ipaddr==2.1.11
ipaddress==1.0.16
IPy==0.83
ipython==2.4.1
itsdangerous==0.24
jdcal==1.0
Jinja2==2.8
jsonpickle==0.9.3
jsonrpclib==0.1.3
keepnote==0.7.8
killerbee==1.0
linereader==1.0.0
logging==0.4.9.6
lxml==3.6.4
M2Crypto==0.24.0
Mako==1.0.4
Markdown==2.6.7
MarkupSafe==0.23
matplotlib==1.5.3
maxminddb==1.2.1
mechanize==0.2.5
mercurial==3.9.2
mimerender==0.6.0
mitmproxy==0.17.1
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.7
nassl==0.12
ndg-httpsclient==0.4.2
netaddr==0.7.18
NfSpy==1.0
nltk==3.2.1
numpy==1.11.2
olefile==0.42.1
openpyxl==2.3.0
OTXv2==1.1
PAM==0.4.2
paramiko==2.0.0
passivetotal==1.0.30
passlib==1.6.5
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathtools==0.1.2
pcapy==0.10.8
pdfminer==20140328
pefile==2016.3.28
pexpect==4.2.0
phply==0.9.1
Pillow==3.3.1
pluginbase==0.4
ply==3.7
poster==0.8.1
prettytable==0.7.2
prompt-toolkit==1.0.8
psutil==4.3.1
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.31
pyasn1==0.1.9
pyasn1-modules==0.0.7
pybloomfiltermmap==0.3.15
pyClamd==0.3.16
pycrypto==2.6.1
pycryptopp==0.6.0.1206569328141510525648634803928199668821045408958
pycurl==7.43.0
pydns==2.3.6
pydot==1.2.3
pyenchant==1.6.7
pyfiglet==0.7.5
PyGithub==1.23.0
Pygments==2.1.3
pygobject==3.22.0
pyinotify==0.9.6
PyJWT==1.4.2
pylibemu==0.3.3
pymssql==1.0.2
pyOpenSSL==16.1.0
pyotp==2.2.1
pyparsing==2.1.10
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.4.0
pyscard==1.9.4
pyserial==3.1.1
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.5.7
pysqlite==2.7.0
pytest==3.0.3
python-apt==1.1.0b5
python-dateutil==2.5.3
python-debian==0.1.29
python-debianbts==2.6.1
python-editor==0.4
python-mimeparse==1.6.0
python-ntlm==1.1.0
python-openid==2.2.5
python-pam==1.8.2
pytz==2015.7
pyusb==1.0.0b2
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
readline==6.2.4.1
reportbug==6.6.6
requests==0.14.2
requests-file==1.4
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
ruamel.ordereddict==0.4.9
scapy==2.3.2
scgi==1.13
selenium==3.0.1
service-identity==16.0.0
shodan==1.5.5
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smalisca==0.2
smmap2==2.0.0
smoke-zephyr==1.0.2
socketpool==0.5.3
SQLAlchemy==1.0.15
sshtunnel==0.1.2
tabulate==0.7.5
tblib==1.3.0
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
terminaltables==3.0.0
threadpool==1.3.2
threatcrowd==0.4
tldextract==2.0.1
tornado==4.4.2
Twisted==16.4.1
tzlocal==1.2.2
Unirest==1.1.7
urllib3==1.16
urwid==1.3.1
uTidylib==0.3
verboselogs==1.5
vinetto==0.7b0
virustotal-api==1.1.2
volatility==2.5
vulndb==0.0.19
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webunit==1.3.10
Werkzeug==0.11.11.dev0
wfuzz==0.0.0
Whoosh==2.7.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xdot==0.5
XlsxWriter==0.9.3
xmlbuilder==1.0
yara-python==3.5.0.999
zenmap==7.31
zim==0.65
zope.interface==4.3.2

#### Device iOS Version
8.4

![image](https://cloud.githubusercontent.com/assets/7777720/20153600/2bd6fd68-a6cc-11e6-8510-35d503bded54.png)

![image](https://cloud.githubusercontent.com/assets/7777720/20153537/d63f5256-a6cb-11e6-876b-89811ac45521.png)

**Comment by marco-lancini** [comment]
Hi @eranvak, from the error code you posted you can see that `plutil` is not installed on device. You can install it manually using Cydia, but if you want to install all the dependencies at once, Needle can help by setting `set SETUP_DEVICE True`
