### ISSUE TITLE
keychain_dump failing with Exception

### ISSUE THREAD

**Issue by tghosth** [mwrlabs/needle#77]
## Issue

keychain_dump was failing with an Exception due to invalid characters in the plist file.

I have done the following and submitted as PR #76:
- Added the additional invalid characters to the list to be removed
- Revamped this code to make it easier to add additional invalid characters
- Added an explanation of the special characters because it took me a while to figure out what the encoding was!
- Added an additional explanation when the Exception is thrown to make it clearer what needs to be done in case someone else finds other invalid characters.

**Comment by marco-lancini** [comment]
Thanks a lot, awesome job as always :)
