### ISSUE TITLE
error on  [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache in IOS8

### ISSUE THREAD

**Issue by javixeneize** [mwrlabs/needle#78]
Hi

I am having an error when running binary/strings function in an IOS8 device from a Mac

[D] [REMOTE CMD] Remote Command: /bin/su mobile -c /usr/bin/uicache

  File "/Users/javi/needle/core/device/device.py", line 120, in _exec_command_ssh
    raise Exception(err_str)
Exception: sh: /bin/su: No such file or directory

------------------------------------------------------------
[!] Exception: sh: /bin/su: No such file or directory.

Checking the py, this is the line creating the issue

      self.remote_op.command_blocking('/bin/su mobile -c /usr/bin/uicache', internal=True)

What is the porpouse of that line of code? By removing it, everything works fine

Thanks

**Comment by marco-lancini** [comment]
Hi @javixeneize, that line comes from this line block:

```
def list_iOS_89(applist):
            # Refresh UICache in case an app was installed after the last reboot
            self.printer.verbose("Refreshing list of installed apps...")
            self.remote_op.command_blocking('/bin/su mobile -c /usr/bin/uicache', internal=True)
            # Parse plist file
            pl = self.remote_op.parse_plist(applist)
            self._applist = pl["User"]
```

Which refresh the cache containing the list of installed apps on device.
I've never occurred into that error. Can you provide more details? (what module where you trying to load, iOS version, full log with `set DEBUG True` enabled, etc)

**Comment by javixeneize** [comment]
Hi Marco

Yes, i understand, but i cant see why it is needed to run that module

As requested, i am running needle from a macosx (el capitan) in an ios8
device jailbroken with taig. I am using binary strings module, but i think
the same call is done in every method

The debug error is as attached. The path for the su binary doesnt exist

Thanks

**Comment by marco-lancini** [comment]
The command: `/bin/su mobile -c /usr/bin/uicache` is used by  Needle to refresh the device's list of installed apps.
Are you sure you don't have a `su` binary in the `/bin` folder?

**Comment by javixeneize** [comment]
Not in el capitan

**Comment by marco-lancini** [comment]
I was referring on your device: the '/bin/su' binary should be present on your jailbroken device

**Comment by javixeneize** [comment]
Ah right. Let me check on monday

**Comment by javixeneize** [comment]
Nevermind.... i see what is the problem now ;) I forgot i renamed the su binary to bypass jailbreak detection

Thanks
