### ISSUE TITLE
Module to install SSL Pinning Kill Switch 

### ISSUE THREAD

**Issue by tghosth** [mwrlabs/needle#81]
### Expected behaviour
Add a module which uses the instructions from [here](http://resources.infosecinstitute.com/ios-application-security-part-36-bypassing-certificate-pinning-using-ssl-kill-switch/) to install the SSL Pinning Kill Switch from [here](https://github.com/nabla-c0d3/ssl-kill-switch2/releases).

### Actual behaviour
This does not currently exist

### Steps which explain the enhancement
The tool has dependencies which can either be installed as part of the module or installed as part of the needle setup as I don't think they are that heavy. Let me know what you think.

Running the module will check the dependencies, pull down the .deb file, install it and respring the device.

Let me know if you think this is an appropriate module to add and if you want me to have a stab at it andif so when you think the dependencies should be installed. My suggestion would be at the same time as needle setup.

**Comment by marco-lancini** [comment]
hey, I was waiting to add it to the list of tools installed with `SETUP_DEVICE` cause I was thinking of adding a Frida script to replace it completely...

**Comment by tghosth** [comment]
So I have had difficulty getting Frida to work right which is why I prefer to use the Kill Switch tweak which is much more straightforward.

**Comment by marco-lancini** [comment]
Ok, I should be able to push it to `develop` tomorrow!

**Comment by marco-lancini** [comment]
Hi @tghosth, this has now been pushed to `experimental`.
I should be able to push it (alongside the Theos integration) to `develop` soon
