### ISSUE TITLE
Clutch2 executable

### ISSUE THREAD

**Issue by B4rD4k** [mwrlabs/needle#85]
Hey, 

I'm running needle on Kali linux i installed all the dependencies in the linux and the IOS device. 
I'm getting an exception that you can see in the ss. please help 

![capture](https://cloud.githubusercontent.com/assets/7777720/20622721/e0f0fdce-b30c-11e6-866c-76c60e47572a.PNG)

**Comment by marco-lancini** [comment]
Hi @B4rD4k,
to fix this try the following:

```
[needle] shell
...
iphone:# chmod +x /usr/bin/Clutch*
iphone:# exit
```

Please let me know if this helps

**Comment by B4rD4k** [comment]
working..
10x
