### ISSUE TITLE
Frida_shell is not spawned 

### ISSUE THREAD

**Issue by B4rD4k** [mwrlabs/needle#88]
Hello again.
I cant spawn a frida shell on some application in my IOS screenshot attached.

![capture](https://cloud.githubusercontent.com/assets/7777720/20640562/0b62ece2-b3ea-11e6-9980-db2439419c19.PNG)

**Comment by marco-lancini** [comment]
Hi @B4rD4k, when opening an issue, could you please post the **full** error log? (by setting `set DEBUG True`)

**Comment by B4rD4k** [comment]
sure,

attaching it right now :)
![capture2](https://cloud.githubusercontent.com/assets/7777720/20641096/3baee496-b3f9-11e6-9e64-ddc782bb959d.PNG)

![capture](https://cloud.githubusercontent.com/assets/7777720/20641095/3617b47c-b3f9-11e6-9033-aa5f91731adc.PNG)

**Comment by marco-lancini** [comment]
thanks! mmh, this error is different from the one you posted above.
Could you please check that both instances of Frida (the one running on your device and the one running on your workstation) are aligned to the same version?

**Comment by B4rD4k** [comment]
My frida linux client is : Frida 8.1.14 
how do i check the frida-server version?

BTW, by using frida -R nameofapp I am succeeding to spawn a shell

**Comment by marco-lancini** [comment]
You can get a shell on the device and then `frida-server --version`

**Comment by B4rD4k** [comment]
OK, after some investigation i did the following:

1. download frida-server https://build.frida.re/frida/ios/bin/frida-server to my device at /usr/sbin/ folder
2. i tried with needle to spawn a shell and do not suceed
3. i tried manualy with frida -U flashlight and it works

just want to mentioned something more, when n i enable the setup_device flaf to true and let him install sth my device is rebooted, this is normal?

**Comment by B4rD4k** [comment]
this is my error with debug mode from needle

![image](https://cloud.githubusercontent.com/assets/7777720/20641308/cf59ebf6-b3fd-11e6-814c-074fdb7fa60d.png)

**Comment by marco-lancini** [comment]
Yes, in the latest release it will install also SSL Kill Switch, and at the end it needs to respring the device (the device is not rebooted, only SpringBoard is).

Regarding your issue with Frida, is the app on foreground?

**Comment by B4rD4k** [comment]
yep

**Comment by B4rD4k** [comment]
Ok actually i solved this..

just replace the -R with -U (dont ask me why just dont working on this version of frida)

10x man. really good tool!!!
