### ISSUE TITLE
[!] Exception: sh: cut: command not found.

### ISSUE THREAD

**Issue by blark** [mwrlabs/needle#9]
Hey there,

Great work! I was just playing around with needle and I tried this:
```
[needle] > use storage/data/files_cachedb
[needle][files_cachedb] > run
[*] Checking connection with device...
[+] Already connected to: 192.168.2.2
[V] Creating temp folder: /var/root/needle/
[*] Configuring device...
[!] Exception: sh: cut: command not found.
[needle][files_cachedb] >
```

I'm not sure which package cut is in, but am I missing some sort of setup option on the device? I have setup device set to true, maybe a package is missing? I would just install it but I'm not sure which package has cut in it and I can't seem to find it with Google. 
``` 
SETUP_DEVICE  True           yes       Set to true to enable auto-configuration of the device (installation of all the tools needed)
```

**Comment by marco-lancini** [comment]
Hey, thanks!
In the latest version (if you cloned the repo today or yesterday) it should have already been fixed. 

If the error still persist, can you please manually install the following packages and try to re-run Needle again?

`iPhone:~ root# apt-get install coreutils coreutils-bin`

**Comment by blark** [comment]
Ahh, I pulled it a few days ago. I will refresh! Thanks.

**Comment by hiburn8** [comment]
Having the same problem with the Lipo binary when using the storage/cache/screenshot module. Needle is trying to run Lipo remotely rather than the version from xcode... but this isnt a package I can find anywhere for iOS and does not have a source/package-name in the constants file. Where is this cheeky monkey hiding? :/

**Comment by hiburn8** [comment]
Scratch that. The DEVICE_SETUP option managed to sort it. Looking at the debug i have no idea how.. there was an APT lock at the time so it shouldnt have been able to do anything.. but whatever.. it works!
