### ISSUE TITLE
Module "script_dump-ui" doesn't work (Script terminated abruptly)

### ISSUE THREAD

**Issue by HenryHoggard** [mwrlabs/needle#95]
## Issue

Note: Application names are modified.

### Expected behaviour
The module `script_dump-ui` should dump the UI hierarchy.

### Actual behaviour

The module returns the error `Script terminated abruptly`.

### Steps to reproduce
1. `use script_dump-ui`
2. `run`

### needle error logs

```
[D] Connected over Wi-Fi
[*] Launching the app...
[D] [REMOTE CMD] Remote Command: open com.hh.iosvuln
[V] Retrieving the PID...
[D] [REMOTE CMD] Remote Command: ps ax | grep -i 'HH iOS.app'
[V] PID found: 1247
[*] Attaching to process: 1247
[*] Parsing payload
[?] Script terminated abruptly
```

#### Workstation Operating System
Debian

#### Python Version
2.7

#### Device iOS Version
9.3

**Comment by marco-lancini** [comment]
Hi @HenryHoggard, does the application have any kind of anti-hooking protection?

**Comment by HenryHoggard** [comment]
@marco-lancini It has no protections implemented.

**Comment by HenryHoggard** [comment]
@marco-lancini Found the fix do you want to push it or shall I create a PR.

**Old:**
```
if(ObjC.available) {
    ObjC.schedule(ObjC.mainQueue, () => {
        const window = ObjC.classes.UIWindow.keyWindow();
        const ui = window.recursiveDescription().toString();
        send(ui);
    });
} else {
    console.log("Objective-C Runtime is not available!");
}
```

**Patch:**
```
if(ObjC.available) {
    ObjC.schedule(ObjC.mainQueue, function() {
        const window = ObjC.classes.UIWindow.keyWindow();
        const ui = window.recursiveDescription().toString();
        send(ui);
    });
} else {
    console.log("Objective-C Runtime is not available!");
```

**Comment by marco-lancini** [comment]
As you prefer, you can push it if you have already fixed it :)

**Comment by marco-lancini** [comment]
thanks @HenryHoggard, this has now been pushed to `develop`
